자동차게임 리뷰 요청드립니다.
kiworkshop/java-racing-car pull request #1
Opened 2021-06-23 04:00 UTC by eunii

안녕하세요. 자동차게임 리뷰 요청드립니다.

2021-06-25 07:42 UTC, jjj0611 requested changes
안녕하세요 다은 선생님 구현해주신 것 잘 봤습니다!

요구사항 작성이나 학습로그도 잘 작성해주셨네요!

몇 가지 고민해보면 좋을 것들에 대해 코멘트 남겼으니 확인 부탁드립니다 :)

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +    }
jae, ,ju 와 같은 방식으로 입력되면 어떻게 될까요?

또한 "공백/null"이라는 메시지를 사용자가 받았을 때 사용자가 어떤 상황인지 인지하기 힘들 수 있을 것 같아요.

좀 더 사용자 친화적인 방향으로 바꿔보면 어떨까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +            throw new RuntimeException("길이");
ditto

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +        return length > CAR_NAME_LENGTH_LIMIT || length == 0;
0이 의미하는 바가 무엇인지 다른 개발자가 알기 쉽게 하려면 어떻게 해야 할까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/MoveCountParser.java
> +            throw new RuntimeException("이동횟수 음수, 글자");
ditto

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/MoveCountParser.java
> +        if (!Pattern.matches(NUMBER_REGEX, inputLine) || Integer.parseInt(inputLine) < 0)
정확하게 작동하고 있나요?
10 이상의 숫자를 넣으면 어떻게 되는지 확인해주세요

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/OutputView.java
> +            System.out.println();
indent가 2인 것 같아요.
프로그래밍 요구사항을 지켜주세요!

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/OutputView.java
> +    InputView inputView = new InputView();
OutputView와 InputView가 강하게 결합되어 있는 것 같아요.

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/OutputView.java
> +    public List<String> askCarNames() {
askCarNames라는 메서드만 보았을 때 응답이 있을거라고 예상하는 사람도 있고,
물어보기만 하고 끝날거라고 예상하는 사람도 있을 것 같은데,

내부적인 구현을 보지 않고, 이 메서드가 하는 일이 무엇인지를 알 수 있도록 해보면 어떨까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/Race.java
> +    }
round 돌리는 역할을 race에서 할까? 하고 생각하다보니
한 라운드마다 출력을 해주어야 하는데 어떡하지? 하고 runOnce() 메서드가 만들어지고,
계속해서 남아있는 메서드인 것 같은데

round를 돌리는 역할은 어디 있는 것이 좀 더 적합할까요?
만약 runRounds(int repeatCount)라는 메서드를 사용하면서도 요구사항을 충족하려면 어떻게 하면 좋을까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/RandomPick.java
> +    }
isMoving이 왜 Math.random()에 10을 곱하고 그게 4보다 큰것을 판단하지?
10은 어떤 의미이고, 4는 어떤 의미일까?
의미와 의도가 잘 드러나지 않은 것 같아요.
좀 더 의미와 의도가 드러나면 좋을 것 같아요 :)

2021-06-25 07:42 UTC, jjj0611 commented on src/test/java/CarNameParserTest.java
> +public class CarNameParserTest {
테스트 작성...👍

2021-06-25 07:42 UTC, jjj0611 commented on src/test/java/CarTest.java
> +        assertThat(car.getPosition()).isLessThanOrEqualTo(1);
car.moveOnRandomPick()의 결과로 자동차의 위치는 1이하가 된다.
이것으로 충분한 테스트가 될 수 있을까요?
랜덤에 대한 테스트는 어떻게 진행되어야 할까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/test/java/MoveCountParserTest.java
> +public class MoveCountParserTest {
입력 값에 대한 검증 테스트가 3가지 밖에 없네요.
입력 값이 될 수 있는 경우의 수는 훨씬 더 많을 수 있을 것 같은데
테스트를 좀 더 보강해보면 어떨까요?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/Race.java
> +    private List<Car> winners = new ArrayList<>();
winners가 이렇게 변수로 생성되어 있으면,
```
getWinners2() {
  return winners
}
```
라는 메서드가 존재하게 되면 무슨 일이 벌어질까요....?

2021-06-25 07:42 UTC, jjj0611 commented on src/main/java/Race.java
> +    private int maxPosition = 0;
ditto

2021-06-25 07:42 UTC, jjj0611 commented on src/test/java/MoveCountParserTest.java
> +    }
현재 해당 parser는 10 이상의 숫자에서는 정상동작을 하지 못하고 있습니다.
돌리는 횟수를 10번 이상 할 수 없는 애플리케이션인거죠.

위와 같은 테스트를 작성했을 경우에 "나는 테스트를 잘 만들었으니 내 프로그램은 문제 없어!"라는 함정에 빠지게 됩니다.
적절한 테스트를 작성하고, 무엇을 검증해야하는지 고민하는 것은 개발에서 굉장히 중요한 부분이라고 생각합니다. :)

2021-06-25 07:42 UTC, jjj0611 commented on README.md
> +- 시도할 횟수만큼 자동차 움직이기
기능 목록은 자세하면 자세할수록 좋아요.
이걸 자세히 작성하다보면 내가 무엇을 개발해야할지, 어떤 부분에 신경을 써야할지 더 자세히 알 수 있거든요.

아직 기능 목록을 작성하는 것이 생소하시겠지만, 조금 더 자세히 작성해나가는 연습을 해보면 좋을 것 같습니다.

2021-06-25 07:42 UTC, jjj0611 commented on STUDYLOG.md
> +- 파일명 변경: shift+f6
학습로그도 잘 남겨주셨네요.

이건 개인적인 바람이지만, 단순히 단축키에 대한 학습로그 뿐만 아니라 기술적 로그도 많이 남겨보시면 어떨까 싶어요.
단축키를 많이 익혀서 도구적 사용성을 증가시키는 것도 매우 중요하지만,
매 미션마다 기술적 배움에 대한 기록도 해보면 좋을 것 같습니다 :)

2021-06-27 22:15 UTC, eunii commented on src/main/java/CarNameParser.java
> +    }
넵 로그 멘트를 수정해보았습니다.

2021-06-27 22:15 UTC, eunii commented on src/main/java/CarNameParser.java
> +            throw new RuntimeException("길이");
넵 로그 멘트를 수정해보았습니다.

2021-06-27 22:15 UTC, eunii commented on src/main/java/CarNameParser.java
> +        return length > CAR_NAME_LENGTH_LIMIT || length == 0;
0 값도 상수로 빼서 무슨 의미를 나타내는지 수정하였습니다

2021-06-27 22:19 UTC, eunii commented on src/main/java/MoveCountParser.java
> +            throw new RuntimeException("이동횟수 음수, 글자");
로그 멘트를 수정하였습니다.

2021-06-27 22:19 UTC, eunii commented on src/main/java/MoveCountParser.java
> +        if (!Pattern.matches(NUMBER_REGEX, inputLine) || Integer.parseInt(inputLine) < 0)
정규식 표현을 수정하였습니다.

2021-06-27 22:51 UTC, eunii commented on src/main/java/OutputView.java
> +            System.out.println();
1 depth 로 줄였습니다.

2021-06-28 00:03 UTC, eunii commented on src/test/java/MoveCountParserTest.java
> +public class MoveCountParserTest {
입력값이 0인경우, 2자리 이상인경우의 테스트 케이스를 추가해보았습니다.

2021-06-28 00:05 UTC, eunii commented on src/main/java/OutputView.java
> +    InputView inputView = new InputView();
OutputView에 선언되어있는 InputView와 Parser들을 삭제하고, 함수 별 파라미터로 주입받게 수정하였습니다.

2021-06-28 00:05 UTC, eunii commented on src/main/java/OutputView.java
> +    public List<String> askCarNames() {
매서드 이름을 좀더 구체적으로 변경하고 파라미터 값을 추가하였습니다.

2021-06-28 00:07 UTC, eunii commented on src/main/java/Race.java
> +    private List<Car> winners = new ArrayList<>();
우승 기준에 따라 winner가 다른 상황이 생길수도 있겠네요. cars를 입력받아 우승 기준에 따른 winner를 새로 생성해서 return하도록 수정하였습니다.

2021-06-28 00:13 UTC, eunii commented on src/main/java/Race.java
> +    private int maxPosition = 0;
cars도 마찬가지로 필요시 각 함수에서 파라미터로 입력 후 리턴하는 형식으로 변경하였습니다.

2021-06-28 00:14 UTC, eunii commented on src/test/java/MoveCountParserTest.java
> +    }
입력값이 0인경우, 2자리 이상인경우의 테스트 케이스를 추가해보았습니다. 빠진 테스트 케이스가 없는지 꼼꼼히 확인해보도록 하겠습니당.

2021-06-28 00:25 UTC, eunii commented on src/main/java/RandomPick.java
> +    }
상수로 빼서 좀더 명확하게 의미가 드러나도록 변수명을 지었습니다.

2021-06-28 01:07 UTC, eunii commented on src/test/java/CarTest.java
> +        assertThat(car.getPosition()).isLessThanOrEqualTo(1);
토요일 수업에서 설명해주신대로 랜덤값을 함수 밖으로 뺐습니다. MovingStrategy인터페이스를 만들어 테스트 할 경우, 리턴값을 true, false로 명시하여 테스트를 진행하게 변경하였습니다.

2021-06-30 05:18 UTC, eunii commented on README.md
> +- 시도할 횟수만큼 자동차 움직이기
네 기능 분류를 자세하게 구성하고, 체크박스로 구현여부 처리해보았습니다

2021-06-30 05:18 UTC, eunii commented on STUDYLOG.md
> +- 파일명 변경: shift+f6
네, 알게 된 개념이나 검색해서 찾아본 내용 등도 추가적으로 정리해보겠습니다~

2021-07-01 12:59 UTC, jjj0611 approved these changes
다은님 리뷰가 늦어서 죄송합니다!
남겨드린 코멘트를 모두 잘 반영해주셨네요 :)

코드리뷰를 한 번 더 하면서 조금 더 생각해볼만한 부분들 코멘트 남겼습니다!
DM으로 이야기 드렸듯이, 먼저 머지 시켜드릴테니 미리 진행하신 2단계 코드에 코멘트 반영하여  2회차 PR 보내주세요!

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/Race.java
> +//    }
더이상 사용하지 않는 메서드는 지워버리면 어떨까요?
불필요한 메서드는 코드를 보는 다른 사람에게 혹은 미래의 나에게 혼란을 줄 수 있지 않을까요?

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +public class CarNameParser {
지금은 Car가 CarNameParser에 매우 의존적인 상황인 것 같아요.
게임의 요구사항 자체가 자동차의 이름은 5를 넘지 않는다.인데, 그냥 new Car("5자이상을넣는다")를 해버리는 순간 자동차는 너무 자연스럽게 생성되겠죠. 왜냐하면 설계를 할 당시에 CarNameParser를 무조건 거친 String만이 자동차를 생성한다!가 지금 구조의 상황이라고 생각이 들어요.

하지만, CarNameParser가 하는 역할(입력 받은 문자열을 구분자 단위로 나누고 나뉘어진 문자가 적합한 길이를 가지고 있는지 체크한다)이 너무 과하지 않나?라는 생각이 조금 드는 부분이 있는 것 같아요.

만약 이 맥락을 모르는 개발자가 왔을 때, 어? 자동차는 그냥 이름을 받아서 생성할 수 있네!라고 생각하여 new Car("5글자가넘는이름");과 같이 생성했다면, 어떤 일이 벌어질까요?

최대한 다른 개발자 혹은 미래의 내가 코드의 히스토리(Car를 생성하기 전에 무조건 CarNameParser를 거쳐야해)를 신경쓰지 않고 개발하도록 하려면 어떻게 하는 것이 좋을까요?

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +            throw new RuntimeException("자동차이름에 공백이나 null이 올 수 없습니다.");
친절한 메시지 👍

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +            throw new RuntimeException("자동차 이름의 길이는 1이상 5이하값을 입력해야 합니다.");
앞에와 같이 내보내려는 메시지는 많이 친절해졌지만,
실제로 예외가 발생했을 때 적절한 메시지가 사용자에게 노출되지 않는 것 같아요!

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +        return length > CAR_NAME_LENGTH_NAX_LIMIT || length == CAR_NAME_LENGTH_MIN_LIMIT;
개인 취향차이지만,
1 <= length && length <= 5;
와 같이 표현되면 더 자연스럽게 코드를 읽을 수 있을 것 같아요 :)
(어디까지나 개인적 취향입니다...ㅎㅎ)

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/CarNameParser.java
> +                .collect(Collectors.toList());
이곳만 스트림을 적용하셨군요.
스트림이 없이는 어떻게 표현될 수 있을까요?

또한, inputLine.replace(SPACE, REPLACEMENT)를 하시면,
사용자가 'hi hi'라는 이름으로 자동차를 만들고 싶어도 'hihi'로만 만들어지지 않을까요? 이걸 의도하신 건가요??

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/OutputView.java
> +            System.out.printf("%-7s : %s\n", car.getName(), totalGo);
자동차의 위치 * "-" 라는 로직이 너무 어렵게 표현된 것 같아요ㅠㅠ
조금 더 직관적으로 위치만큼 이동된 상태를 표현해주는 방식은 없을까요?
어떻게하면 조금 더 직관적으로 이해되는 코드를 작성할 수 있을까요?

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/OutputView.java
> +        System.out.println(resultNames.toString().substring(0, resultNames.length() - 2) + "(이)가 최종 우승했습니다.");
-2를 하신 이유는 누가 마지막인지 모르고 마지막인 경우에는 ", "가 붙은 것을 떼야하니 이렇게 작성이 된 것 같아요!
지금 printWinners는 public하게 열려있기 때문에 누구든 쓸 수 있는 메서드가 될텐데, 누군가가 printWinners(Collections.emptyList());로 호출을 하면 어떤 일이 일어날까요?

또 위와 같은 로직에서 마지막에 ", "를 빼주는 것이 코드를 읽기 좋을까요??
마지막에 ", "를 붙여주지 않는 것이 코드를 읽기 좋을까요??
혹은 조금 더 직관적으로 코드를 작성하기 위한 다른 방법은 없을까요?

2021-07-01 12:59 UTC, jjj0611 commented on src/main/java/Race.java
> +    private int maxPosition = 0;
maxPosition도 List<Car> winners와 같은 현상이 일어날 수 있지 않을까요?
만약에 10회 시도 후에 getWinners를 한 번 했는데 1등의 position이 10이었고,
모든 자동차들의 position을 0으로 초기화한 후에 5회 레이스를 돌리고, 다시 getWinners가 호출되면 어떤 일이 벌어질까요?

2021-07-01 13:00 UTC, merged