자동차 경주 commit내역 수정
kiworkshop/java-racing-car pull request #11
Opened 2021-07-07 03:53 UTC by eunii

#### git 사용법

1. chreey-pick

   git의 commit을 선택적으로 다루는것

   git checkout branchBase 베이스로 깔고 싶은 브랜치로 이동한다

   git cherry-pick 커밋해시코드 -> 해당 커밋만 현재 브랜치에 가져온다.(해시코느는 git log로확인가능)

2. rebase

   작업내역의 베이스를 원하는 커밋으로 변경할 수 있다

   베이스를 변경하고 싶은 브랜치로 checkout한다

   git regase -i 브랜치명 

   파일이 열리면 삭제하고 싶은 커밋 앞을 d로 변경 후 :w를 눌러 저장한다

2021-07-08 01:16 UTC, jjj0611 requested changes
안녕하세요 다은 선생님.
요구사항에 맞게 잘 구현해주셨네요.
패키지 분리에도 신경을 쓰셨네요 👍

고민해볼만한 부분에 대해서 코멘트 남겼으니 확인해주세요~

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/domain/RacingGame.java
> +    private int tryNo = 0;
지난 리뷰 때 말씀드린 것에서 다시 수정이 생겼네요.
RacingGame에서 maxPosition과 winners, cars, carNames, tryNo 등의 상태 값을 가졌을 때
발생할 수 있는 문제가 무엇일까요?
왜 다시 상태값을 가지게 되었을까요?

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/domain/RacingGame.java
> +    }
메서드의 언어적 의미와 실제 메서드가 수행하는 것의 일치하는지 고민해보면 좋을 것 같아요.
메서드 시그니처를 만든다는 것은 그 메서드가 의미하는 바를 가지고 (미래의 나를 포함한) 다른 개발자가 편히 사용할 수 있게 되는데요.
만약 메서드 시그니처를 신뢰할 수 없다면 해당 코드를 신뢰할 수 없게 됩니다.

Car의 maxPosition과 이 게임 내 전역에 존재하는 maxPosition을 비교해서 같으면 두번째 인자로 들어온 winners에 추가하고,
더 크면 winners를 비우고 다시 차를 추가하고, 전역에 있는 maxPosition의 값을 바꾼다.
== 우승자를 업데이트 한다.

이 의미의 합치가 일어나는지 고민해보면 좋을 것 같아요 :)

더불어 지금 maxPosition같은 경우는 RacingCarGame 내에 존재하는 필드를 그냥 사용하고 있고,
List<Car> winners는 (RacingCarGame 내에 존재함에도) 메서드 파라미터를 받아서 사용하고 있는데 
일관성이 지켜지면 좋을 것 같습니다.

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/domain/RacingGame.java
> +    }
진행중인가? == 시도 횟수를 한 횟수 줄이고, 시도 횟수가 0보다 크거나 같은지 본다.

이 의미와 합치되는지 고민해보면 좋을 것 같습니다 :)

조금 과장된 이야기라고 생각하실 수 있겠지만, isRunning을 판단하고 게임을 한 회수 돌렸는데 (메서드 명만 보니) 횟수 차감을 안하네?
하고 누군가가 반복문 안에서 횟수를 차감하게 된다면 어떤 일이 벌어질까요?

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +    private static MoveCountParser moveCountParser = new MoveCountParser();
final 키워드에 대해 한 번 찾아보시고 고민해보시면 좋을 것 같아요.

또한, static 한 변수에 대한 네이밍 컨벤션을 지켜주세요!

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +    }
자 이 내용이 input view로 넘어와서 질문을 드립니다.
input view와 output view의 역할적 구분은 어떻게 되어야 할까요?
"실행 결과"를 출력하는 것은 output view의 역할이고,
"시도할 횟수는 몇 회인가요?"를 출력하는 것은 input view의 역할일까요?

2021-07-08 01:16 UTC, jjj0611 commented on src/main/java/view/OutputView.java
>      }
사용하고 있는 곳이 있을까요?
해당 클래스에 어떤 메서드는 static하게 어떤 메서드는 static하지 않게 만들었는데 이유가 있을까요?

2021-07-08 01:16 UTC, jjj0611 commented on src/test/java/domain/RacingGameTest.java
> +        racingGame.setCars(cars);
carName으로 RacingGame을 생성하고, racingGame에 다른 자동차들을 set하는 이유가 있을까요?
직접 set하는 메서드를 사용하지 않고 테스트를 해보면 어떨까요?

2021-07-08 01:16 UTC, jjj0611 commented on src/test/java/domain/RacingGameTest.java
>          Car car3 = new Car("car3", 5);
자동차의 position을 받아서 생성하고 있네요.
실제 프로덕션 코드에서는 사용되지 않는 생성자로 보이는데요.

MoveStrategy를 만들어서 사용하고 있는 이유가 무엇일까요?
기존에 random하게 자동차를 전진시키다보면 어떤 자동차가 어떤 위치에 있는지 모르게 되고,
그럼 우승자를 선정하는 로직을 테스트하기가 어려워지기 때문이었죠.

그래서 MoveStrategy를 만들면 자동차의 전진/스탑을 Strategy를 구현함으로써 의도적으로 판단 가능하게 만들어줄 수 있었는데요.
그렇다면 이 position과 함께 생성되는 생성자는 사라져도 되지 않을까요?
전략 패턴을 주입하여 주었을 때 어떤 이점이 있는지 고민해보면 좋을 것 같아요!

2021-07-15 07:34 UTC, eunii commented on src/main/java/domain/RacingGame.java
> +    private int tryNo = 0;
winner와 carNames, maxPosition은 Race에서 필요한 값이 아니라 삭제했습니다..
다만 cars와 tryNo는 레이스에서 몇 라운드를 돌지, 어떤 차들이 경주를 할지는 Race에 필요한 속성값이라고 생각해서 남겨놨습니다.

2021-07-15 07:36 UTC, eunii commented on src/main/java/domain/RacingGame.java
> +    }
Race에서는 경주를 실행하고, 경주 결과(RaceResult)를 리턴해주는 상태로 리펙터링하였고, RaceResult에 경기 현황, 우승자를 계산하는 함수로 추가하였습니다.

2021-07-15 07:39 UTC, eunii commented on src/main/java/domain/RacingGame.java
> +    }
네 메서드명을 정의할때 내부 함수에서 어떤 일이 일어나는지 명확하게 알 수 있도록 고민해보겠습니다!!

2021-07-15 07:58 UTC, eunii commented on src/main/java/view/InputView.java
> +    private static MoveCountParser moveCountParser = new MoveCountParser();
* 접근제어자 final
- 변수: 변수를 상수화 시킨다. 즉 한번 값이 결정된 변수의 값은 변경이 불가능하다.
- 클래스란: 클래스를 final로 선언한다면, 이 클래스를 상속하는 것을 허용하지 않겠다는 뜻이다.
- 메소드란: 메소드를 final로 선언한다면, 이 메소드의 오버라이딩을 허용하지 않겠다는 뜻이다. 클래스는 상속이 가능하되 해당 메소드는 오버라이딩이 불가능하다.
 * static final: 클래스 내외부에서 참조용으로 선언된 변수
위 내용을 참고하여 Scanner를 final static으로 선언했습니다.

2021-07-15 08:15 UTC, eunii commented on src/test/java/domain/RacingGameTest.java
> +        racingGame.setCars(cars);
Race에서 CarNames를 받아 Cars 를 생성하는 로직을 생성자에 추가하였습니다.

2021-07-15 08:17 UTC, eunii commented on src/main/java/view/OutputView.java
>      }
해당 함수는 삭제하고 printRounds 이 처음 호출될때 "실행결과"를 출력하도록 수정하였습니다.

2021-07-15 08:19 UTC, eunii commented on src/test/java/domain/RacingGameTest.java
>          Car car3 = new Car("car3", 5);
해당 생성자는 삭제하였습니다. 자동차에있는 전진전략을 조작?하여 테스트케이스를 변경하였습니다.

2021-07-15 08:35 UTC, eunii commented on src/main/java/view/InputView.java
> +    }
outPutView로 출력 내용들을 이동하였습니다. 원래는 Controller에서 outputView, inputView를 호출하는 했었는데, inputView에서 outputView를 호출하는 내용으로 변경했습니다.

2021-07-20 15:10 UTC, jjj0611 requested changes
다은 선생님 수정해주신 부분 잘 봤습니다
코드가 이전에 비해서 많이 깔끔해졌네요 👍 

조금 고민해볼만한 부분들 코멘트 남겼으니 확인 부탁드려요~!

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/domain/Race.java
> +    }
tryNo을 -1로 입력하면 어떻게 되나요?

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/domain/Race.java
> +    private RaceResult raceResult = new RaceResult();
tryNo이나 RaceResult를 Race의 필드로 갖고 있는 것에 대해서 한 번 더 고민해보시면 좋을 것 같아요!
tryNo을 받아서 생성된 레이스는 그 tryNo에 종속적인 레이스가 되겠죠.
그런데 만약에 한 레이스를 시도 횟수만 달리해서 여려번 진행을 하게 되는 경우는 어떨까요?
예를 들어 public RaceResult run(int tryNo);
이라는 메서드가 존재한다면 좀 더 유연하게 경주를 여러번 실행 할 수 있겠죠.
이처럼 강하게 결합되어 있을수록 재활용하기가 어려워집니다.

무조건적으로 결합을 끊는 것도 좋지 않지만, 조금 더 유연한 구조를 위해 객체간의 결합을 최소한으로 가져가는 방향을 고민해보시면 좋을 것 같아요 :)

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/domain/Race.java
> +        raceResult.setRoundResult(new Cars(cars));
경기 결과를 라운드마다 저장하는 방식을 사용하고 있네요 👍 

조금 과한 이야기일 수도 있지만 한 번 고민해보세용~
현재 Car객체는 자동차 경주를 직접 진행(move)하는 역할을 하고 있습니다.
만약 누군가 의도적으로 결과를 조작하기 위해 바깥에서 raceResult.getLast().getCarByName("jjj").move()를 의도적으로 1000번 호출한다고 생각해보세요.

의도한 것과는 전혀 다른 결과가 나오겠죠? 다은 선생님이 생각하는 raceResult에 담겼으면 하는 내용은 한 라운드에 대해서
어떤 자동차들이 어떤 위치에 있었는가?에 대한 내용일 것 같은데요.
그렇다면 `어떤 자동차들이 어떤 위치에 있었는가?`에 대한 정보를 담을 객체를 만들면 어떨까요?
지난 시간에 불변에 대한 이야기도 조금 나눴으니 그 시점의 자동차의 위치를 바꿀 수 없도록 만드는거죠.
그렇다면 RaceResult는 누구도 마음대로 변경할 수 없는 그 시점의 SanpShot이라는 것을 보장할 수 있게되죠.

이처럼 객체가 무엇을 해야해?라는 그 역할에 따라 조금 더 세분하게 나눠보시면 앞으로 많은 도움이 될 거에요 :)

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/domain/RaceResult.java
> +    }
이 역시도 winners를 field로 가지고 있어야 하는 이유가 뭘까?에 대한 고민을 해보시면 좋을 것 같아요.
저번에도 한 번 말씀드렸던 것 같은데,
```
publc List<Car> getWinners2() {
  return this.winners;
}
```
를 하면 의도와 상관없이 비어있는 List<Car>를 만날 수 있게 됩니다.
현재 다은 선생님이 만들어두신 getWinners();는 fields의 상태 값을 바꾸는 역할과 필드를 보내는 역할을 동시에 하고 있어요.
두번째 호출할 때 다시 계산하지 않아도 돼서 성능이 더 좋지 않냐고 말씀하실 수도 있지만,
이러한 성능차이는 미비하다고 생각합니다.

위와 관련하여 1단계에서 리뷰해드렸던 내용 참고 부탁드려요

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/domain/Cars.java
> +    private static CarNameParser carNameParser = new CarNameParser();
InputView, OutputView, RacingGameController 등은 static 한 메서드로 풀고,
해당 CarNameParser는 객체를 생성해서 메서드 호출하는 이유가 있을까요?

2021-07-20 15:10 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +    private static MoveCountParser moveCountParser = new MoveCountParser();
CarNameParser와 ditto

2021-07-20 15:10 UTC, jjj0611 commented on src/test/java/domain/RaceTest.java
> +    void 차가_확률만큼_전진한다() {
아래 테스트가 확률만큼 전진하는 것을 테스트하는건가요????
정확한 테스트명을 적어주시면 좋을 것 같아요!

2021-07-22 12:52 UTC, eunii commented on src/main/java/domain/Race.java
> +    }
tryNo를 inputValication에서 검증해서 넘겨 받았었는데, Race에서 검증하도록 수정하였습니다.

2021-07-22 12:53 UTC, eunii commented on src/main/java/domain/Race.java
> +    private RaceResult raceResult = new RaceResult();
추천해주신대로 재사용할 수 있도록 RaceResult 필드에서 없애고 리턴해주는 방식으로 수정하였습니다. 훨씬 더 유연한 구조가 된것 같아요 ㅎㅎ

2021-07-22 12:56 UTC, eunii commented on src/main/java/domain/Race.java
> +        raceResult.setRoundResult(new Cars(cars));
레이스 라운드 결과만 저장하는 CarResult, CarResults를 생성후, setter를 없애고 생성자에서 주입받는 형태로  변경했습니다. RaceResult클래스에서 레이스 최종 결과를 final로 설정했습니다.

2021-07-22 12:56 UTC, eunii commented on src/main/java/domain/RaceResult.java
> +    }
winner를 필드에 선언하지 않고, getWinner를 호출할때마다 계산해서 넣어주는 방식으로 수정했습니다.

2021-07-22 12:57 UTC, eunii commented on src/main/java/domain/Cars.java
> +    private static CarNameParser carNameParser = new CarNameParser();
이건 방식을 제가 잘 몰라서 섞어서 썼는데ㅜ 해당 클래스도 static으로 바로 호출하게 변경하였습니다.

2021-07-22 12:58 UTC, eunii commented on src/main/java/view/InputView.java
> +    private static MoveCountParser moveCountParser = new MoveCountParser();
이건 방식을 제가 잘 몰라서 섞어서 썼는데ㅜ 해당 클래스도 static으로 바로 호출하게 변경하였습니다.

2021-07-22 12:58 UTC, eunii commented on src/test/java/domain/RaceTest.java
> +    void 차가_확률만큼_전진한다() {
레이스가 실행되면 최종 결과를 받는것을 체크하는 함수 함수명을 좀더 명확하게 수정하였습니다.

2021-07-23 10:45 UTC, jjj0611 commented on src/main/java/domain/RacingGame.java
> +    private int tryNo = 0;
tryNo은 Race에 필요한 속성값일 수 있지만, 그렇다고 하여 무조건 field로 들고 있지 않아도 될 수 있습니다.
예를 들어 Race가 Cars만 들고 있고, tryNo을 인자로 받아서 레이스를 진행할 수도 있겠죠?

2021-07-23 10:47 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +    private static MoveCountParser moveCountParser = new MoveCountParser();
넵 만약 static하게 생성해둔 scanner와 carNameParser등이 변수로서 추후에 변경될 가능성이 있다면 final 키워드를 붙이지 않아도 됩니다.
근데 static하게 선언했다는 것은 전역적으로 사용 가능하게끔 만들겠다는 의미인데, 전역적 사용가능한 객체가 가변적이다라고 했을 때 무시무시한 일이 벌어지게 됩니다. 난 분명 A인줄 알고 사용했는데 누군가가  B로 바꿔놨다고 생각해보세요!

그래서 보통 static하게 선언되는 객체는 final로서 불변한 방향성으로 많이들 개발하고 있습니다 :)

2021-07-23 10:50 UTC, jjj0611 approved these changes
다은 선생님 반영해주신 부분과 reply 남기신 부분 잘 보았습니다!
몇가지 코멘트 드렸고, 확인 부탁드려요! 👍 
2단계는 이만 머지하겠습니다.
그동안 고생하셨습니다 :)

2021-07-23 10:50 UTC, merged