[자동차 경주 2단계] 리뷰 요청 드립니다.
kiworkshop/java-racing-car pull request #13
Opened 2021-07-09 18:39 UTC by chunghyeon-kim

## 학습로그
___
##### 1. MVC 패턴
  - [MVC 패턴](https://velog.io/@ljinsk3/MVC-%ED%8C%A8%ED%84%B4)
    - 도메인 로직과 UI 로직을 분리하여 유지보수가 용이하다.

2021-07-10 08:33 UTC, Deocksoo requested changes
안녕하세요 충현선생님,
구현해주신 부분 잘 읽어보았어요. 첫 미션으로 보내주셨던 때보다 훨씬 읽기 편하고, 테스트하기에도 쉽게끔 개선되었네요 👍 덕분에 편하게 읽어볼 수 있었어요.
추가로 고민해보시면 좋을 만한 부분들 코멘트 남겨드렸으니, 확인 한 번 부탁드려요 :)

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/controller/RacingController.java
> +    static View view = new View();
클래스들이 잘 분리되었군요. 👍 
그런데 static 변수로 선언한 이유는 무엇인가요?
접근제어를 하지 않아도 괜찮나요?

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/domain/Car.java
> +    MoveStrategy moveStrategy;
접근제어

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/domain/Car.java
> +    public Car(String name, int score, MoveStrategy moveStrategy) {
외부에서 움직이는 전략을 주입받도록 하였군요 👍

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/domain/Race.java
> +            System.out.println(car);
view를 따로 분리해주셨던 것 같은데, 이 부분은 따로 남겨놓은 이유가 있나요?

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근제어

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/view/View.java
> +    OutputView outputView = new OutputView();
접근제어

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/view/OutputView.java
> +    CarRacingService carRacingService = new CarRacingService();
접근제어

2021-07-10 08:33 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/domain/CarRacingServiceTests.java
> +        CarRacingService service = new CarRacingService();
👍 
하나의 테스트 케이스만 보더라도 그 안에서 무엇을 테스트하는지 알기 쉽게 작성되었군요.

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/domain/ThresholdFourStrategy.java
> +    public boolean forward(int randomNumber) {
간단한 로직이지만, 반드시 테스트 되어야 할 것 같은 메서드네요.

2021-07-10 08:33 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/controller/RacingController.java
> +            carNames = service.splitCarNamesByComma(view.getUserInput(message));
이제 view 를 담당하는 객체가 마련되었는데요.
그렇다면 자동차의 이름을 comma 기준으로 쪼개는 것은 비즈니스 로직에 가까울지, view의 로직에 가까울지 한 번 더 고민해보시는 것도 좋겠네요.

2021-07-10 08:33 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/domain/CarTests.java
> +        Car car = new Car("TestCar", 0, new ThresholdFourStrategy());
지금과 같은 테스트도 물론 좋은 테스트에요. 간결하고, 검증하려는 바를 잘 검증하고 있어요.
그런데 한 가지 굳이 흠을 잡자면, 이 테스트가 여전히 ThresholdFourStrategy라는 구현체에 의존하고 있다는 점이에요.
만약에 움직이는 전략이 4에서 3으로 바뀌게 되면 이 테스트는 변경된 전략에 대해서도 잘 검증할 수 있는 테스트인가요?
그렇지 않을 것 같은데, 그러면 그 때마다 자동차에 대한 테스트도 일일이 모두 변경해주어야 할까요? 그게 괜찮은 방법일까요?
자동차에서 움직이는 전략을 분리해 낸 이유는 무엇인가요?
분리되었다면, 분리된 목적에 맞도록 검증하는 더 좋은 방법이 있지는 않은가요?

2021-07-19 05:15 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/controller/RacingController.java
> +    static View view = new View();
static 메서드인 메인메서드에서 사용하기 위해 static으로 선언했습니다.
생각해보니 클래스변수일 필요가 없을 것 같아 메서드 내부로 이동시켰습니다.

2021-07-19 05:15 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/domain/Car.java
> +    MoveStrategy moveStrategy;
접근제어자 수정했습니다.

2021-07-19 05:16 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근제어자 수정했습니다.

2021-07-19 05:16 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/view/View.java
> +    OutputView outputView = new OutputView();
접근제어자 수정했습니다.

2021-07-19 05:17 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/view/OutputView.java
> +    CarRacingService carRacingService = new CarRacingService();
접근제어자 수정했습니다.

2021-07-19 05:18 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/domain/CarRacingServiceTests.java
> +        CarRacingService service = new CarRacingService();
네. 말씀해주신대로 수정했더니 테스트가 명확해졌습니다.

2021-07-19 05:18 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/domain/ThresholdFourStrategy.java
> +    public boolean forward(int randomNumber) {
테스트 추가했습니다.

2021-07-19 05:20 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/controller/RacingController.java
> +            carNames = service.splitCarNamesByComma(view.getUserInput(message));
InputView 클래스로 이동했습니다.

2021-07-19 05:31 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/domain/CarTests.java
> +        Car car = new Car("TestCar", 0, new ThresholdFourStrategy());
자동차에서 움직이는 전략을 분리해 낸 이유는 추후 전략을 바꾸어야 할 상황이 생겼을 때 구현체만 교체해서,
전략을 사용하는 부분의 코드를 수정하지 않기 위함입니다. (전략패턴)

테스트클래스의 클래스변수로 인터페이스 타입의 참조변수 moveStrategy를 선언해서 
테스트메서드들이 그 moveStrategy를 이용해 테스트를 수행하도록 변경했습니다.

추후 전략이 변경된다면 테스트메서드를 일일이 변경할 필요 없이 moveStrategy만 다른 구현체로 변경해주면 될 것 같습니다.

2021-07-19 05:32 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/domain/Race.java
> +            System.out.println(car);
OutputView 클래스로 이동했습니다.

2021-07-21 16:03 UTC, Deocksoo approved these changes
충현선생님 안녕하세요, 
고민해야 할 부분들이 적지 않으셨을텐데, 끝까지 잘 마무리하시느라 고생 많으셨어요.
레이어에 맞게 적당히 분리되고, 테스트도 잘 짜여진 코드가 된 것 같네요. 
정리가 정리되면 좋을 만한 부분이나 생각해보실 만한 부분 추가로 리뷰 남겨드렸으니, 참고 부탁드려요.
그 동안의 미션이 충분한 연습이 되셨을 것 같아 미션은 이만 마무리하도록 할게요.
고생 많으셨어요 💯

2021-07-21 16:03 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/domain/CarRacingService.java
> +
CarRacingService에서 splitCarNamesByComma, getGameCount와 같은 메서드들은 도메인과 약간 관련이 있는 것처럼 보이기도 하지만, 사용자의 입력과 조금 더 많은 연관이 있는 부분일 수 있겠어요. View로 분리하는 것도 고려해보면 좋겠네요 :)

2021-07-21 16:03 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/domain/CarTest.java
> +    private final MoveStrategy moveStrategy = new ThresholdFourStrategy();
이 부분은 전달하려고 하는 바가 약간 다르게 전달된 것 같네요 :)
변수로 추출하여 한 곳에서 변경할 수 있도록 한 것은 좋지만, CarTest가 ThresholdFourStrategy에 의존하고 있는 것은 여전하지요.
이런 경우에는 익명클래스를 이용해봐도 좋은데요. Random_값_정지 테스트 안에서 ThresholdFourStrategy 대신 다른 Strategy를 로컬 변수로 새로 선언해서 사용하는 방식으로도 테스트해볼 수 있을 것 같아요. 가령, 반드시 앞으로 이동하는 Strategy, 절대 앞으로 이동하지 않는 Strategy 등을 테스트 용도로 생성해서 이용하면 ThresholdFourStrategy 와는 전혀 관계 없이 Car만 온전히 테스트할 수 있겠죠.

하지만 지금 테스트도 충분히 좋은 테스트에요. 실제로 현업에서 코드를 작성할 때에도 편의를 위해 위 테스트처럼 이미 만들어놓은 객체를 활용하는 경우가 많아요. 연습을 위해 극단적인 분리를 제안드려 본 것이니, 모든 테스트가 반드시 이렇게 되어야 한다고 생각하지는 않으셔도 괜찮을 것 같아요.

2021-07-21 16:05 UTC, merged