자동차 경주 게임 1단계 (최희진님과 페어프로그래밍)
kiworkshop/java-racing-car pull request #2
Opened 2021-06-23 07:02 UTC by chunghyeon-kim

## 학습로그
___
##### 1. 테스트 코드 작성
  - [@BeforeAll](https://beanbroker.github.io/2019/10/05/Java/test_after_before)
    - 테스트 코드 실행 전에 딱 한번만 실행된다.
    - Junit4 의 @BeforeClass가 @BeforeAll 로 바뀌었다.
___
##### 2. JAVA 프로그래밍
  - [자바 스트림](https://ryan-han.com/post/java/java-stream)
  - [싱글톤(Singleton) 패턴](https://woowacourse.github.io/javable/post/2020-11-07-singleton)
    - 싱글톤 패턴으로 해볼까 싶어서 찾아보았다.
___
##### 3. Lombok 라이브러리
  - [롬복 라이브러리 추가](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=vefe&logNo=222072718782)
    - 롬복 라이브러리를 사용해볼까 싶어서 찾아보았지만 빌드가 잘 되지 않아서 그냥 두었다.
    - 롬복 라이브러리 추가시 annotationProcessor 도 설정해 주어야 한다.
  - [@AllArgsConstructor, @NoArgsConstructor](https://athena7.tistory.com/entry/Lombok-NoArgsConstructor-AllArgsConstructor-RequiredArgsConstructor)
    - 생성자 생성 어노테이션
___
##### 4. Builder 패턴
  - [빌더 패턴](https://devlog-wjdrbs96.tistory.com/207)
  - [Lombok을 이용한 빌더 패턴](https://zorba91.tistory.com/298) 
    - 생성자에 인자가 많을 때는 빌더 패턴을 고려해본다.
___
##### 5. 리모트 저장소 추가
  - [git remote 명령어를 이용한 리모트 저장소 추가 및 활용](https://velog.io/@leyuri/Git-remote-리모트-저장소-저장소-추가하는-법)

2021-06-24 15:48 UTC, Deocksoo requested changes
충현선생님 안녕하세요!
상수처리도 잘 되어있고, 메서드도 기능단위로 분리해서 깔끔하게 작성해주신 것 같아요 👍 
스트림을 활용해서 로직 흐름을 간결하게 가져가려는 시도들도 무척 좋네요.
코드 재미있게 잘 읽었어요, 읽으면서 몇몇 부분들 코멘트 남겨두었으니 확인 한 번 부탁드려요 :)

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Car.java
> +    public Car() {
기본 생성자는 어디에 사용되나요?
불필요한 생성자나 메서드들은 정리해주는 것이 좋을것 같아요

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Car.java
> +    public void setScore(int score) {
메서드의 이름과 메서드가 하는 동작이 다른 것 같은데요,
이름만 보았을 때에는 입력하는 숫자로 set 해줄 것 같은 이름이네요.
조금 더 좋은 이름 없을까요~?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +        String[] carNames = service.getCarNames(inputCarName);
메서드 이름만 보아서는 무슨 일을 하는지 잘 와닿지 않아요.
무슨 일을 하는지 더 명시적으로 드러내줄 수 있지 않을까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +        String[] carNames = service.getCarNames(inputCarName);
carNames의 타입으로 String 배열을 사용하는 이유는 무엇인가요?
java Collection을 사용해보면 어떨까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +     * Scanner 통해 사용자에게 입력 받는다.
보다 깨끗한 코드를 작성하기 위한 가이드 중 하나로 **불필요한 주석은 남기지 않는 것이 좋다** 는 제안이 있죠.
주석을 남길 때에는 신중해야 하는데, 왜 그럴까요?
이 주석은 반드시 필요한 주석인가요?
어떤 경우에 주석이 필요할까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        race.setGameCount(gameCount);
setter 메서드의 사용은 가급적이면 지양하는 것이 좋은데요,
setter를 통해 직접 값을 세팅하도록 만들면 어떤 문제가 있을까요?
객체지향이라는 큰 주제 안에서 한 번 고민해보시면 좋을 것 같아요 :)

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +     * 자동차 이름 문자열 길이를 확인한다.
위 코멘트를 통해 말씀드렸듯, 다른 모든 주석들에 대해서도 한 번 없애는 것을 고민해보시면 좋을 것 같아요.
메서드 이름만으로 충분히 동작을 유추할 수 있으면 좋겠어요.

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            car.setScore(compareRandom(randomNumber));
지금은 자동차가 앞으로 전진할지 말지 campareRandom 메서드에서 판단을 하고, 
판단의 결과물을 모두 결정해서 넘겨주고 있군요 :) 
자동차가 스스로 판단해서 전진할 수 있도록 하면 어떨까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        int max = cars.stream().max(Comparator.comparing(Car::getScore)).get().getScore();
메서드를 chaining해서 연결하는 경우에 읽기가 어려워지는 경우가 많아요.
줄바꿈으로 구분해주시면 어떨까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        int max = cars.stream().max(Comparator.comparing(Car::getScore)).get().getScore();
Optional에서 get() 의 활용은 지양하는 것이 좋은데요, Optional을 보통 어떤 스타일로 사용하는지 한 번 찾아보시면 좋을 것 같아요 :) (Optional에 익숙하지 않으시면 설명들이 다소 난해할 수 있어요.)

ps. mapToInt를 활용해서 IntStream으로 만들면 max값 비교하는 것이 보다 수월해지지 않을까요~?

2021-06-24 15:48 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        printWinner(getWinners(race.getCars()));
winners를 구하기 위해 객체에서 자동차들을 꺼내지 말고, 객체에 메시지를 던지면 어떨까요?

2021-06-24 15:48 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    @DisplayName("자동차 이름을 입력을 받는다")
테스트가 검증하려고 하는 내용을 보다 명시적으로 드러낼 수 있는 이름이면 좋겠어요.

2021-06-24 15:48 UTC, Deocksoo commented on README.md
> +### 기능 요구사항
👍

2021-06-29 11:50 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/Car.java
> +    public Car() {
삭제했습니다 :)

2021-06-29 11:50 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/Car.java
> +    public void setScore(int score) {
addScore로 변경했습니다.

2021-06-29 11:58 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +        String[] carNames = service.getCarNames(inputCarName);
getCarNames를 splitCarNamesByCommaToArrayList로 변경했습니다

carNames로 String배열을 사용한 이유는 String클래스의 split메서드의 리턴 타입이 String배열이라서
깊은 생각 없이 그냥 똑같은 타입으로 사용했습니다

ArrayList로 변경했습니다.

2021-06-29 12:06 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +     * Scanner 통해 사용자에게 입력 받는다.
주석을 관리하는 것도 비용이라서 최소화하는 게 좋다고 생각됩니다.
메서드 시그니처를 적절하게 만들어서 주석을 사용하지 않고도 의미전달이 된다면 더 좋은 코드라고 할 수 있을 것 같습니다.

코드만 보고서는 알 수 없는 사정이나 History를 알려야 할 경우 주석이 필요하다고 생각됩니다.
또한 앞으로 구현해야 할 기능이나 경고 등을 주석으로 작성하는 게 적절할 것 같습니다.

2021-06-29 12:09 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        race.setGameCount(gameCount);
변경되지 않는 인스턴스에 대해서 setter로 접근이 가능해져 객체의 일관성, 안정성을 보장할 수 없습니다.

(https://velog.io/@sezeom/Getter-Setter-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0 참고했습니다)

2021-06-29 12:09 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +     * 자동차 이름 문자열 길이를 확인한다.
주석을 삭제하고 메서드 이름을 적절하게 변경했습니다 :)

2021-06-29 12:11 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            car.setScore(compareRandom(randomNumber));
compareRandom 메서드를 car 클래스로 이동했습니다.

객체의 책임과 캡슐화에 대해서 한 번 더 생각해보게 되었습니다.

2021-06-29 12:16 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        int max = cars.stream().max(Comparator.comparing(Car::getScore)).get().getScore();
줄바꿈으로 구분되도록 수정했습니다.

getWinners 메서드를 race 클래스로 이동하고 mapToInt를 사용했습니다.
orElseThrows 메서드를 사용해 Optional객체가 비어있으면 예외를 던지도록 수정했습니다.

2021-06-29 12:17 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        printWinner(getWinners(race.getCars()));
getWinners 메서드를 race 클래스로 이동했습니다.

객체의 책임과 캡슐화에 대해서 한 번 더 생각해보게 되었습니다.

2021-06-29 12:17 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    @DisplayName("자동차 이름을 입력을 받는다")
"입력받은 자동차 이름의 개수를 확인한다" 로 수정했습니다.

2021-06-30 13:45 UTC, Deocksoo requested changes
안녕하세요 충현선생님,
제안드렸던 수정사항들 잘 반영해주신 것 같아요 :) 코드가 훨씬 깔끔해졌네요 👍 
그런데 코드의 어떤 부분을 개선하면, 그 부분을 개선함으로 인해 또 다른 부분을 개선 할 수 있는 가능성이 열리기도 하죠. 그 반복되는 과정 속에서 얻는 것들이 있으실 것 같아서 코멘트를 조금 더 남겨보았어요.
수고스러우시겠지만, 한번 더 확인 부탁드려요 :)

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +            carNames = service.splitCarNamesByCommaToArrayList(getUserInput(message));
메서드 이름이 메서드가 하는 일을 조금 더 잘 드러내게 된 것 같아요 👍 
다만, 메서드 이름에는 타입이 포함되지 않도록 하는 것이 어떨까요?
return 타입을 보고 알 수 있는 사항이기도 하고, return 타입이 변경되었을 때 메서드명을 변경해줘야 하니 관리 포인트가 두 군데나 생기게 될 것 같아요 :) 이 때 만약 메서드명을 변경하는 것을 깜빡하면 이름이 거짓말을 하는 메서드가 되어버리겠죠.

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +    public static void main(String[] args) {
지금도 그렇게 복잡한 코드는 아니지만, main 메서드 안에서 일어나는 일들이 약간 번잡해 보이기도 하네요.
main 메서드 안에서 벌어지는 일들을 조금 더 작은 단위의 메서드들로 나눠보면 어떨까요?

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +                .Builder(gameCount, carNames.stream()
parameter로 들어가는 부분에 로직이 섞여있으면 읽기에 조금 어려워지는 것 같아요.
메서드 내부 변수로 빼낼 수 있지 않을까요?

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            car.addScore(car.stopOrGoByRandomNumber(random.nextInt(10)));
지금 car.addScore 메서드를 호출할 때 넘겨줄 parameter가 필요한데요, 그 parameter는 또다시 car의 메서드를 호출하여 만들어지는 결과물이군요.
그러면 car 내부에서 모두 처리해줄 수 있지 않을까요?

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Race.java
> +        int max = cars.stream()
👍 
마찬가지로 다른 곳들도 체이닝 된 부분이 있으면 줄을 띄워주시면 좋을것 같아요.

2021-06-30 13:45 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Race.java
> +    public static class Builder {
빌더 패턴을 시도해보셨군요 :) 좋은 시도인 것 같아요.
빌더 패턴의 장점을 조금 더 살려볼 수 있을것 같은데, 패턴의 의미에 맞게 사용될 수 있도록 메서드를 조금 더 추가해보면 어떨까요?
java 빌더 패턴에 대해서 조금 더 찾아보셔도 좋을 것 같아요.

2021-06-30 13:45 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +public class CarRacingTests {
이전에는 CarRacing에 있던 메서드들이 리펙터링 과정에서 특정 객체 안쪽으로 이동한 것들이 있죠.
그러면 테스트 클래스도 각각의 클래스별로 따로 만들어서 테스트할 수 있도록 나누면 어떨까요?
그러면 테스트를 작성하기에도, 보기에도 훨씬 편해질 것 같아요.

2021-06-30 13:45 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    static Car car = new Car("TestCar", 0);
테스트에 사용되는 객체를 테스트 클래스 내부의 static 변수로 선언하셨군요.
이렇게 되면 서로 다른 두 테스트에서 하나의 변수를 반복하여 사용하게 될 수도 있겠어요.
지금은 그렇지 않지만, 어떨 때에는 하나의 테스트가 다른 테스트의 수행 여부로 인하여 영향을 받을 수도 있지 않을까요?
**각각의 테스트는 다른 테스트의 영향을 받지 않고 독립적으로 동작할 수 있도록 하면 좋을 것 같아요.** 
**그리고 각 테스트 메서드를 읽어 볼 때 그 안쪽에 적혀있는 코드만으로 무엇을 테스트하고 있는지 명확하게 알 수 있으면 좋겠어요.**
그렇게 되도록 수정해보면 어떨까요?

2021-06-30 13:59 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        race.setGameCount(gameCount);
좋은 접근인 것 같아요. 👍 
더불어 setter 메서드를 열어두면, 어떤 값을 set 해주기 위해서 바깥에 그 값을 계산하는 로직이 생겨버릴 수도 있죠.
그리고 이 계산로직을 보지 못하면 또다른 곳에서 해당 클래스를 사용할 때, 값을 set 해주기 위해 앞서 만든것과 동일한 계산 로직을 또 만들 수도 있겠죠.
결국 setter 메서드는 코드 중복을 양산하고 객체의 존재 의미를 퇴색시키는 주범이 될 가능성이 높아요.

2021-07-05 08:13 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +            carNames = service.splitCarNamesByCommaToArrayList(getUserInput(message));
splitCarNamesByComma로 수정했습니다 :)

2021-07-05 08:15 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacing.java
> +    public static void main(String[] args) {
자동차 이름을 조건에 맞을 때 까지 반복해서 입력받는 부분을 ensureCarNameCondition 메서드로 분리하고
시도 횟수를 조건에 맞을 때 까지 반복해서 입력받는 부분을 ensureGameCountCondition 메서드로 분리했습니다.

2021-07-05 08:18 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +                .Builder(gameCount, carNames.stream()
네. 확실히 parameter에 로직이 섞여있으니 가독성이 많이 떨어지는 것 같습니다.
메서드 내부 변수로 분리했습니다.

2021-07-05 08:20 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            car.addScore(car.stopOrGoByRandomNumber(random.nextInt(10)));
Car 클래스에 addScore 메서드와 stopOrGoByRandomNumber 메서드를 수행하는
raceByRandomNumber 메서드를 추가했습니다.

2021-07-05 08:21 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/Race.java
> +        int max = cars.stream()
메서드 체이닝 코드를 작성할 때 항상 줄을 띄우는 습관을 들이도록 하겠습니다.

2021-07-05 08:26 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/Race.java
> +    public static class Builder {
Race 클래스의 멤버변수가 gameCount와 cars 두 개 뿐이라 빌더 패턴이 좀 어색하게 적용된 것 같습니다.
찾아본 바로는 필수 멤버는 Builder클래스의 생성자에, 선택 멤버는 다른 메서드로 분리해서 입력받도록 작성하게 되어있습니다.
생성자 매개변수에서 gameCount를 제외하고 gameCount메서드로 입력받도록 수정했습니다.

혹시 놓친 점이 있다면 알려주시면 감사하겠습니다 :)

(https://lee1535.tistory.com/104 참고했습니다)

2021-07-05 08:27 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +public class CarRacingTests {
CarTests, RaceTests, CarRacingServiceTests 3개의 테스트 클래스들로 분리했습니다.
클래스별로 테스트 클래스를 나누어서 작성하는 것이 관리하기에 훨씬 편할 것 같습니다. 👍

2021-07-05 08:48 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    static Car car = new Car("TestCar", 0);
@BeforeEach 애너테이션을 사용해서 테스트 메서드들이 독립적으로 동작할 수 있도록 수정했습니다.
테스트 메서드들의 의미전달이 더 잘 되도록 변수이름들을 수정했습니다.

2021-07-05 14:08 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Race.java
> +    public static class Builder {
말씀해주신 부분이 맞습니다. 개인적으로는 parameter가 많은 경우 빌터패턴을 사용할 때에 어떤 필드에 어떤 값이 들어가는지 보다 명시적으로 드러내기 위해 사용하기도 합니다. parameter가 많은 경우에는 몇 번째에 뭐가 들어가고 있는지 바로 알기가 어려운 경우도 종종 생기기 때문인데요. 가령, 

```
Race.builder()
    .gameCount(gameCount) 
    .cars(cars)      
    .build()
```

와 같은 형태로 많이 사용하고 있습니다. 
그리고 말씀해주신 
> 찾아본 바로는 필수 멤버는 Builder클래스의 생성자에, 선택 멤버는 다른 메서드로 분리해서 입력받도록 작성한다

와 같은 부분은 명시적으로 패턴을 사용할 수 있는 좋은 방법인 것 같습니다 :) 보통 작업할 때에 Lombok의 도움을 많이 받게 되면서 위 예시 코드와 같이 패턴화된 사용을 많이 보이게 되는 것 같은데요, 짚어 주신 것처럼 필수 parameter를 builder를 통해 사용하려면 [이렇게](https://stackoverflow.com/questions/29885428/required-arguments-with-a-lombok-builder) 사용하는 방법도 있네요. Lombok annotation의 사용 예시보다는, Lombok을 적용한 이후 어떻게 사용되는지 참고하셔서 구현해보시는 것도 좋을 것 같습니다.

사족이 길었네요. 패턴의 사용이나 Lombok 사용이 중요한 것은 아니니, 길었지만 대충 흘려 읽어주시면 감사드리겠습니다.
정리하여 말씀드리면 
1. 기본적인 Builder 패턴의 구조는 잘 구현해주신 것 같습니다.
2. Lombok을 많이들 사용하시는데, 그 때문에 빌더 사용은 전형적으로 보이는 패턴이 있고, 참고해보시면 좋겠다.
정도 되겠습니다.

2021-07-05 14:14 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/CarTests.java
> +        car = new Car("TestCar", 0);
👍 
이렇게 Car를 새로 할당되도록 선언하는 것도 좋지만, 테스트 대상인 Car는 각 테스트에서 local 변수로 선언하여 사용하는 것도 고려해보시면 좋을 것 같습니다. 

**Test 해야 할 대상 객체**와 **Test fixture**에 어떤 차이가 있는지, 각각은 어떻게 선언하는 것이 읽기에 더 좋을지 한 번 고민해보셔요 :)

2021-07-05 14:18 UTC, Deocksoo commented
피드백을 다소 많이 드렸는데, 꼼꼼히 읽어봐주시고 깊게 고민해 주신 흔적이 많이 보이네요.
훨씬 깔끔한 코드가 되도록 잘 리펙토링 해주신 것 같습니다 👍 
두 주간 구현하시느라 고생 많으셨습니다. 추가로 고민해보시면 좋을 것 같은 부분들 코멘트 드렸으니, 참고 한 번 부탁드려요.
제출해주신 부분까지는 이만 머지하도록 하겠습니다.

2021-07-05 14:19 UTC, Deocksoo approved these changes
피드백을 다소 많이 드렸는데, 꼼꼼히 읽어봐주시고 깊게 고민해 주신 흔적이 많이 보이네요.
훨씬 깔끔한 코드가 되도록 잘 리펙토링 해주신 것 같습니다 👍
두 주간 구현하시느라 고생 많으셨습니다. 추가로 고민해보시면 좋을 것 같은 부분들 코멘트 드렸으니, 참고 한 번 부탁드려요.
제출해주신 부분까지는 이만 머지하도록 하겠습니다.

2021-07-05 14:19 UTC, Deocksoo commented on src/test/java/com/mission2/racingcar/CarTests.java
> +    void beforeEach() {
👍
이렇게 Car를 새로 할당되도록 선언하는 것도 좋지만, 테스트 대상인 Car는 각 테스트에서 local 변수로 선언하여 사용하는 것도 고려해보시면 좋을 것 같습니다.

Test 해야 할 대상 객체와 Test fixture에 어떤 차이가 있는지, 각각은 어떻게 선언하는 것이 읽기에 더 좋을지 한 번 고민해보셔요 :)

2021-07-05 14:20 UTC, merged

2021-07-05 14:27 UTC, Deocksoo commented on src/main/java/com/mission2/racingcar/Car.java
> +    public void addScore(int score) {
클래스 내부에서만 사용되는 메서드는 private 메서드로 선언해주시는 것이 어떨까요?
java method access level 과 관련하여 한 번 찾아보시고, 적용해보셔도 좋을 것 같아요.

2021-07-09 12:25 UTC, chunghyeon-kim commented on src/main/java/com/mission2/racingcar/Car.java
> +    public void addScore(int score) {
접근제어자는 가능한 한 좁은 범위로 설정하는 게 변경시 유리하다는 점을 확인했습니다.
private으로 변경했습니다.

2021-07-09 12:31 UTC, chunghyeon-kim commented on src/test/java/com/mission2/racingcar/CarTests.java
> +    void beforeEach() {
Test fixture는 여러 테스트에서 공통적으로 사용하는 객체입니다.
Junit에서 제공하는 애너테이션을 이용해서 Test fixture를 선언하면 코드 중복을 방지할 수 있습니다.

Test해야 할 대상 객체는 개별 테스트 내에서 local변수로 선언하는 것이 가독성이 더 좋다고 생각됩니다.
CarTests와 CarRacingServiceTests에서 Test 대상 객체를 각 테스트에서 local 변수로 선언하도록 수정했습니다.