자동차 게임 리뷰요청드립니다.
kiworkshop/java-racing-car pull request #3
Opened 2021-06-23 07:36 UTC by Ariel429

2021-06-27 16:11 UTC, kwangilcho requested changes
정애님! 자동차게임 요구사항에 따라 잘 구현하셨네요! 😀 
고생많으셨어요. 고민해볼 만한 지점들에 코멘트를 남겨두었습니다.
확인하셔서 다음 코드 제출 시 반영해주시면 감사하겠습니다!

아래는 코드 전반에 대한 리뷰 사항입니다.

모든 메서드의 접근제한자가 public이네요.
테스트를 작성하기 위해 이렇게 되어있는 것으로 보여요.
public 제한자의 본연의 목적에 부합하는 코드일까요? 
공개된 메서드의 의미에 대해서 한 번 생각해보시면 좋겠습니다.

InputView에서 반드시 콘솔을 통한 사용자 입력을 받아야만 게임을 실행할 수 있게 되는데요.
테스트가 어려워진 시작점이었을 것이라 보여요.
객체 중심으로 테스트를 더 잘 작성하려면 어떻게 개선하면 좋을까요?

무엇을 테스트 할 것인가? 고민해보시면 좋겠어요.
모든 메서드를 꼭 다 테스트해야할까요?
테스트는 어떤 목적을 달성하기 위해 존재할까요?

스터디 로그를 작성하기로 한 것으로 알고 있는데요.
이번 피드백을 통해 학습하게 될 내용을 자세히 한 번 기록하여 남겨보면 어떨까요?

2021-06-27 16:11 UTC, kwangilcho commented on README.md
> +# 구현해야할 기능 목록
구현해야할 기능 목록을 투두리스트 형태로 작성해주셨군요. 👏

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/RacingCarGame.java
> +    public static void main(String[] args) {
View(InputView, OutputView) 와 Controller 객체를 중심으로 어플리케이션이 작성되었네요.
혹시 어떤 기준으로 두 객체로 나누셨을까요?
객체별로 기대하였던 역할과 책임에 대해서 고민해보신 것을 한 번 정리하여 작성해주시면 감사하겠습니다.

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/RacingCarGame.java
> +        GameController gameController = new GameController(inputView, outputView);
이름만 보았을 때는 Input이 입력이고 Output이 출력이니 Output이 결과물로 나와야할 것으로 기대되는데요.
함께 입력으로 들어가고 있네요. 어떤 것을 의도하셨을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    private static final int ADVANCE_CONDITION = 4;
Condition이라는 표현이 모호합니다. 더 정확한 단어로 표현해보아요~

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    private static final int ADVANCE = 1;
필요한 상수일까요? 다른 방법으로 전진 시 값이 증가하는 것을 구현할 수 없을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/view/InputView.java
> +public class InputView {
InputView가 가진 메서드들은 테스트가 없네요. 테스트를 보강해보면 어떨까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/view/InputView.java
> +        StringUtils.isBlank(inputNames);
StringUtils.isBlank를 활용하였으나 결과값에 대해서 사용하지 않았네요.

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/view/InputView.java
> +        int inputRounds = scanner.nextInt();
정수가 입력으로 들어오지 않으면 어떻게 될까요? 사용자의 입력은 믿을만한 것이 되지 않습니다.
어떻게 하면 더 안전한 프로그램을 작성할 수 있을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/view/OutputView.java
> +    private static final StringBuilder STRING_BUILDER = new StringBuilder();
StringBuilder를 사용하셨네요! 혹시 어떤 장점이 있어 사용하신 것일까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +        return Arrays.stream(names.split(DEFAULT_DELIMITER))
Stream을 활용해 split과 trimming 체인을 잘 구현하셨네요! 👍

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    private void validateDelimiter(String names) {
이 유효성 검증이 저는 조금 어색하다 생각이 들었어요.
게임의 규칙상 레이스이기에 2대 이상의 자동차가 입력되어야하는 것이 규칙인데요.
구분자의 존재성 검증으로 규칙에 대해 간접적으로 판단하는 것으로 보여요.
해당 규칙을 더 잘 드러내는 방법은 무엇일까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +                .anyMatch(name -> name.length() > MAX_NAME_LENGTH);
anyMatch 사용 👍

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +                .anyMatch(name -> name.length() > MAX_NAME_LENGTH);
혹은 아래와 같은 사용도 가능합니다.
예외처리까지 stream 체이닝 안 쪽으로 끌고 들어오는 방법입니다.
작성하신 코드와 다른 점은 중간에 상태값이 만들어지지 않는 다는 점이 있지만 제 생각에 큰 차이는 없습니다.
두 방법 모두 괜찮아 보입니다.
```suggestion
            .filter(name -> name.length() > MAX_NAME_LENGTH)
            .findAny()
            .ifPresent(overLength -> {
                throw new RuntimeException("이름은 5자 이하여야 합니다.");
            });
```

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +        Map<String, Integer> cars = new LinkedHashMap<>();
Map을 그대로 사용하고 보니 자동차의 이름과 포지션을 기록해둔 엑셀 시트를 들고다니는 느낌이 드네요. 😅 
조금 더 객체지향적으로 코드를 작성해보면 어떨까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +                    .forEach(car -> {
아앗! 들여쓰기 규칙 위반 삐~

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +                    .forEach(car -> {
최대 들여쓰기 제한이 있었죠? 😁

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    public boolean checkAdvanceCondition(int randomNumber) {
이 메서드의 몸체 내용이 상당히 직관적이라 생각이 드는데요.
따로 메서드화 하신 이유가 있을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    public int generateRandomNumber() {
이 메서드의 몸체 내용이 상당히 직관적이라 생각이 드는데요.
따로 메서드화 하신 이유가 있을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +            car.setValue(car.getValue() + ADVANCE);
setter를 사용하지 않고 해결할 수 있는 방법은 없을까요?
객체의 상태 변경에 대해 고민해보시면 좋겠어요!

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    public List<String> announceWinners(Map<String, Integer> cars) {
결과에 대한 출력이 어떤 것은 Controller 객체에 어떤 것은 OutputView에 있네요.
어떤 기준으로 그것을 나누셨을까요?
책임이 분산되지 않는 것이 좋은 객체 설계라면 어떤 객체에 그 역할이 모여야할 지 고민해보면 좋겠네요.

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +    public int findWinningPosition(Collection<Integer> carPositions) {
Map의 values()를 받으면서 파라미터가 컬렉션으로 가져오게 되었네요.
사실 리스트가 들어올 것을 기대하고 작성된 코드라 보여지는데요.
IntStream을 공부해보시면 훨씬 간결하게 최대값을 추출해낼 수도 있답니다!

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/controller/GameController.java
> +        return rounds;
race를 호출하는 입장에서 어떤 반환 값을 기대할까요?
현재 코드 흐름상 rounds는 반환이 0 외에는 될 수 없을 것으로 보이는데요.
유의미한 정보량이 있는 반환 값일까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/main/java/view/OutputView.java
> +        System.out.printf("%-5s : %s\n", car.getKey(), STRING_BUILDER.toString());
출력 포매팅 👍

2021-06-27 16:11 UTC, kwangilcho commented on src/test/java/controller/GameControllerTest.java
> +        assertThatThrownBy(() -> gameController.split(names))
assertj 의 예외 검증 메서드를 잘 활용하셨네요! 👏

2021-06-27 16:11 UTC, kwangilcho commented on src/test/java/controller/GameControllerTest.java
> +    @DisplayName("입력받은 이름에 `,`이 포함되지 않을 경우 예외가 발생한다.")
위에서도 코멘트했지만, 유효성 검증의 목적이 입력받은 이름에 ,이 포함되어있지 않은 경우를 걸러내는데 목표가 있을까요?

2021-06-27 16:11 UTC, kwangilcho commented on src/test/java/controller/GameControllerTest.java
> +        assertThat(names.size()).isEqualTo(expected);
사이즈만 검증을 하셨는데 실제로 ,를 기준으로 정확히 '파싱만 잘 되었는지(내용물의 변형이 있지는 않은지)' 검증해야하지 않을까요? 그리고 split 메서드 내부에서 trim 까지 함께 기능 구현하셨으니 trim이 정상적으로 되었는지도 검증해야할 것으로 보여요.

2021-06-27 16:11 UTC, kwangilcho commented on src/test/java/controller/GameControllerTest.java
> +    @DisplayName("0-9 중 하나의 숫자를 random하게 생성하여 반환한다.")
'랜덤하게'라는 것은 어떻게 테스트할 수 있을까요?
아래에서 검증은 뽑혀 나온 숫자가 0과 9사이의 자연수인지만 검증하고 있네요.

2021-06-29 06:05 UTC, Ariel429 commented on src/main/java/RacingCarGame.java
> +        GameController gameController = new GameController(inputView, outputView);
함께 입력으로 들어가고 있다는 부분이 이해가 가지않는데, 어떤 방향으로 리팩토링하면 좋겠다고 생각하셨는지 조금 더 설명해주실 수 있으실까요?

2021-06-29 06:08 UTC, kwangilcho commented on src/main/java/RacingCarGame.java
> +        GameController gameController = new GameController(inputView, outputView);
GameController 객체 생성시에 inputView, outputView가 함께 들어가서 만들어지고 있어요.
`new GameController(inputView, outputView);`

2021-06-29 06:21 UTC, Ariel429 commented on src/test/java/controller/GameControllerTest.java
> +    @DisplayName("0-9 중 하나의 숫자를 random하게 생성하여 반환한다.")
'랜덤하게'라는 부분을 테스트할 필요가 있다는건, 혹시 자바 내부 메서드를 사용할 때에도 그 진위등을 의심해야한다는 걸까요? 해당 질문을 잘 이해하지 못하겠어서 설명을 조금 더 해주시면 좋겠습니다!

2021-06-29 07:10 UTC, kwangilcho commented on src/test/java/controller/GameControllerTest.java
> +    @DisplayName("0-9 중 하나의 숫자를 random하게 생성하여 반환한다.")
아 테스트 설명의 `@DisplayName("0-9 중 하나의 숫자를 random하게 생성하여 반환한다.")` 문장을 그대로 이해했을 때
0-9 중 하나의 숫자를 / random하게 생성하여 / 반환한다
에서 random하게 생성하여 라는 것을 테스트하고 있는 것으로 기대되는데요,

실제 테스트 내용은 0-9 중 하나의 숫자를 / 반환한다 만 검증이 된 것 같아 남겨두었어요.

자바에서 제공되는 메서드를 검증하라는 뜻은 아니었고,
랜덤과 같은 제어 불가능한 환경에 대해서 어떻게 테스트할 수 있을 지 고민해보면 좋겠네요 :)

2021-07-23 09:10 UTC, closed without merging