Jiwoo kimm
kiworkshop/java-racing-car pull request #4
Opened 2021-06-23 07:43 UTC by jiwoo-kimm

안녕하세요!

자동차 경주 과제 제출합니다.
피드백 부탁드립니다!

2021-06-23 15:48 UTC, KIMSIYOUNG requested changes
안녕하세요🙂 각 요구사항들에 맞게 프로그램을 너무 잘 만들어주셨네요! 

개인적인 의견들이 있어서 코멘트 남겼습니다🙂 같이 고민해보는 시간이 되면 좋겠고, 의견 나누면서 선택적으로 반영해주세요 👏

추가로 커밋 단위는 잘 분리해주신 것 같은데 메시지가 불명확한 것들이 조금 있어요! (예를 들면 리팩토링 < 등 ) 요런 부분들도 다음엔 조금 더 어떤 작업을 했는지 명확한 메시지로 남겨주시면 좋을 것 같습니다ㅎㅎ

2021-06-23 15:48 UTC, KIMSIYOUNG commented on STUDYLOG.md
> +### 테스트 메서드 네이밍
스터디 로그 👏

요번 미션에서 TDD를 배웠다고 들었는데요! TDD에 대해서도 간략하게 정리해보는건 어떨까요? 

TDD를 하며 느낀점이나, 아쉬웠던 점, 어려웠던 점 등을 적는 것도 좋을 것 같아요.

2021-06-23 15:48 UTC, KIMSIYOUNG commented on README.md
> +- 자동차 이름 입력받기
어떤 기능을 구현할 것인지 명확하게 보여서 좋은 것 같아요! 

다만 어떤 기능이 완료됐는지 체크까지 해주면 조금 더 좋을 것 같습니다.

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/Game.java
> +    private static List<Car> buildCarList(List<String> carNames) {
객체/메소드 분리 및 통신 👏

build라는 단어보다는 개인적으로는 create/generate 등의 단어가 조금 더 어울리는 것 같은데 어떻게 생각하세요? (개인 취향입니다..ㅎㅎ)

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    private String name;
2021/06/23 값의 생성과 동시에 초기화 되고 재할당 되지 않는다면 `final` 키워드도 함께 사용하면 어떨까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    private int position;
`name`에 `final`을 붙인다면 `position`은 어떻게 하면 좋을까요? 

변경되는 값이기 때문에, `final`없이 현재처럼 가져가도 되고, `final`을 사용하고 불변객체로 사용하는 형태도 가능할 것 같은데요. Car를 불변객체로 구현하려면 어떤 형태로 구현할 수 있을까요? 그리고 어떤 방식을 선택하셨고 왜 그렇게 선택하셨는지 의견 같이 주시면 좋을 것 같습니다🙂

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    public String getPositionString() {
해당 메소드가 도메인(`Car`)에 있어야하는 로직이라고 판단하시는 이유가 있을까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +        this(name, 0);
현재 `AllArgs` 생성자를 요 라인과 테스트에서만 사용하고 있어요!

테스트에서 사용하지 않았다면 `AllArgs` 접근제어자를 `private`으로 사용할 수 있을 것 같은데, 테스트를 위한 프로덕션 코드가 생기는거에 대해서 어떻게 생각하시나요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Race.java
> +    public List<Car> getCars() {
롬복을 부분적으로 적용한 이유가 있으실까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Race.java
> +        if (car.getPosition() == maxPosition) {
조금 더 객체지향적으로 풀어보면 어떨가요? 

지금은, 레이스가 자동차를 가져와서 값을 비교하고 있는데, 특정 값이 같은지는 자동차 객체가 담당할 수 있지 않을까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +public class CarNameParser {
`CarNameParser`는 유틸패키지에 있는데 자동차의 이름은 1~5자라는 도메인 로직을 알고 있어요. 요 부분은 도메인이 담당해야하는 로직이 아닐까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +        if (isNullOrEmpty(inputLine))
[코드컨벤션 7-4를 보면 ](https://myeonguni.tistory.com/1596) if문이 하나라도, 중괄호를 사용해주는게 좋을 것 같아요🙂

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +        if (isLengthOutOfBound(name.length()))
`isNameValid`는 이름이 적절하지 않은 경우 `false`값을 줄거라고 기대되는데요! 예외보단 반환값을 주는게 어떨까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +        return length > CAR_NAME_LENGTH_UPPER_BOUND || length < CAR_NAME_LENGTH_LOWER_BOUND;
매직넘버 상수화 👏

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/game/util/RandomPick.java
> +    public static boolean isMove() {
해당 클래스는 `RandomPick`이라는 유틸성 의미의 네이밍을 지니고 있지만, 내부적으로는 도메인 로직을 명확하게 알고 수행하고 있어요. 

어떻게 분리하면 좋을까요? 추가로 RandomPick에 대한 테스트는 없는데요! 랜덤한 수를 어떻게 테스트할 수 있을까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/view/InputView.java
> +    final Scanner scanner = new Scanner(System.in);
해당 인스턴스 변수에 접근제어자가 `package-private`인 이유가 있을까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/view/OutputView.java
> +    public void printWinners(List<Car> winners) {
`List<Car> winners` 는 좋은 네이밍으로, 어느정도 이해가 되지만 아래와 같은 의문이 들어요. 이런 의문을 없앨 수 있도록 한 번더래핑해서 도메인으로써 가져가는건 어떨까요?

- 왜 우승자가 여러명이지? 다중 우승이 되나?
- List면 동일한 자동차 두개가 우승일수도 있는건가?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/view/OutputView.java
> +        System.out.print(winnerNames.substring(0, winnerNames.length() - 2));
마지막에 ,를 제거하기 위한 로직인데 이 부분을 읽는 사람이 바로 이해할 수 있을까요?  

유의미한 의미를 전달할 수 있도록 변경해보아요!

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/test/java/game/domain/CarTest.java
> +        assertThat(car.getPosition()).isLessThanOrEqualTo(1);
해당 테스트는 갔을수도 있고, 아닐수도 있다를 테스트할 수 있는데요! 

이 경우 항상 안가더라도 테스트는 정상 동작하게 됩니다. 우리가 원하는 기능인 갈 때도 , 안 갈때도 테스트 하려면 어떤 식으로 할 수 있을까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/test/java/game/util/CarNameParserTest.java
> +    void Given_EmptyInputLine_When_parseCarNames_Then_RuntimeExceptionThrown() {
빈칸이 여러개인 경우는 어떻게 될까요? 요 부분도 문제 없는 입력이라고 간주하셨다면 반영 안하셔도 괜찮습니다.🙂

다만 요런 애매한 케이스에 대해서는 테스트를 작성해주시면 보는 사람이 더 의도를 파악하기 좋을 것 같아요.

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/test/java/game/util/RaceCountParserTest.java
> +        String inputLine = "-1";
실행횟수는 음수가 될 수 없다에서, 0이 들어오는 경우는 어떨까요? 

현재는 전체 우승처리 되는데요. 이걸 의도하셨다면 테스트로 본인의 의도(0은 모두 우승한거로 간주)를 드러내면 좋을 것 같아요. 예상한 케이스가 아니라면 다른 처리를 해주셔도 좋구요!

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/test/java/game/domain/CarTest.java
> +    void Given_Name_When_newCar_Then_CarInstanceCreatedWithPositionZero() {
테스트 네이밍 원칙 👏 

저는 테스트 이름을 개인적으로 아래와 같이 한글명을 선호하는데요, 해당 네이밍이 더 가독성이 높으신가요?

- Junit5: @DisplayName("새로운 자동차를 생성할 수 있고 초기 위치는 0으로 초기화된다") 
- Junit4 : 새로운_자동차를_생성할수있고_초기위치는_0으로_초기화된다

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/view/dto/ViewDto.java
> +//    public ViewDto(String carNamesInput, String raceCountInput) {
사용하지 않는 코드는 삭제해주세요🙂

2021-06-23 15:48 UTC, KIMSIYOUNG commented on src/main/java/view/dto/ViewDto.java
> +@Builder
빌더를 사용하신 이유가 있으실까요?

2021-06-23 15:48 UTC, KIMSIYOUNG commented on build.gradle
> +sourceCompatibility = 11
String::repeat 메소드를 위해 버전을 올리신거일까요? 

아시다시피 실제로는 버전올리는게 쉽지 않은데, repeat메소드는 유틸성으로 직접 구현해서(비슷하게) 사용해보는 건 어떨까요?

2021-06-25 16:25 UTC, jiwoo-kimm commented on src/main/java/game/Game.java
> +    private static List<Car> buildCarList(List<String> carNames) {
builder에서 따와서 build라고 적은 거였는데, generate가 더 맘에 들어서 변경했습니다!

2021-06-25 16:26 UTC, jiwoo-kimm commented on README.md
> +- 자동차 이름 입력받기
넵 다음 미션부터는 체크리스트로 구현할 기능 목록을 작성해보겠습니다!

2021-06-25 16:27 UTC, jiwoo-kimm commented on STUDYLOG.md
> +### 테스트 메서드 네이밍
넵! 별도로 미션 회고 글을 작성해보려 하는데 TDD도 내용에 포함하겠습니다

2021-06-25 16:28 UTC, jiwoo-kimm commented on src/main/java/game/domain/Car.java
> +    private String name;
앗 인텔리제이에서도 `final` 붙이라고 추천해주네요! 변경했습니다.

2021-06-25 16:57 UTC, jiwoo-kimm commented on src/main/java/game/domain/Car.java
> +    public String getPositionString() {
`position`을 노출하지 않기 위해 String 값을 넘기려고 했었어요! 근데 `"-"` 자체가 `View`에서 표현해야 하는 내용이라는 부분을 놓친 것 같습니다ㅎㅎ.. `View`에서 `position`을 받아서 출력하도록 수정했습니다!

2021-06-25 17:04 UTC, jiwoo-kimm commented on src/main/java/game/domain/Car.java
> +        this(name, 0);
이렇게 하면 안 될 것 같다고 생각은 했는데, 우선 다른 것부터 하고 돌아오겠다고 생각을 하다보니 그냥 넘어가게 됐습니다..ㅎㅎ..

`AllArgs` 생성자를 없애고, `position`을 증가시켜서 특정 `position`에 위치한 `Car` 객체를 테스트에서 사용할 수 있도록 수정했습니다!

2021-06-25 17:12 UTC, jiwoo-kimm commented on src/main/java/game/domain/Race.java
> +    public List<Car> getCars() {
검토할 때 놓친 것 같습니다..! `Race` 클래스에도 롬복 적용했습니다!

2021-06-25 17:15 UTC, jiwoo-kimm commented on src/main/java/game/domain/Race.java
> +        if (car.getPosition() == maxPosition) {
넵 `Car` 객체가 `maxPosition`을 받아서 boolean 값을 리턴하도록 수정했습니다!

2021-06-25 17:18 UTC, jiwoo-kimm commented on src/main/java/game/util/CarNameParser.java
> +        if (isNullOrEmpty(inputLine))
넵 수정했습니다!

2021-06-25 17:31 UTC, jiwoo-kimm commented on src/main/java/view/InputView.java
> +    final Scanner scanner = new Scanner(System.in);
`private`을 붙이는 것을 깜빡했습니다! 외부에서 접근할 필요가 없으니 `private`이 더 적절한 것 같습니다

2021-06-25 17:34 UTC, jiwoo-kimm commented on src/main/java/view/OutputView.java
> +        System.out.print(winnerNames.substring(0, winnerNames.length() - 2));
`removeCommaAtTheEnd` 메서드로 해당 로직을 빼도록 수정했습니다!

2021-06-25 17:40 UTC, jiwoo-kimm commented on src/main/java/game/util/CarNameParser.java
> +        if (isLengthOutOfBound(name.length()))
넵 해당 메서드에서는 boolean 값을 반환하도록 바꾸고, 별도로 길이 검증하는 로직을 수행하도록 수정했습니다!

2021-06-25 17:47 UTC, jiwoo-kimm commented on src/test/java/game/util/CarNameParserTest.java
> +    void Given_EmptyInputLine_When_parseCarNames_Then_RuntimeExceptionThrown() {
넵 아예 String을 trim() 처리를 해서 빈칸 입력은 무시하도록 했어요!
애매해보이는 관련 테스트들을 더 명확하게 수정해보았습니다

2021-06-25 17:50 UTC, jiwoo-kimm commented on src/test/java/game/domain/CarTest.java
> +        assertThat(car.getPosition()).isLessThanOrEqualTo(1);
랜덤 유틸은 `Car`가 아닌 다른 도메인에서 호출하고, `Car`에서는 움직이는 기능만 수행하도록 테스트와 프로덕션 코드를 수정했습니다!

2021-06-25 17:56 UTC, jiwoo-kimm commented on src/test/java/game/util/RaceCountParserTest.java
> +        String inputLine = "-1";
앗 0은 생각하지 못했습니다! 0 역시 예외를 던지도록 수정했습니다.

2021-06-25 17:59 UTC, jiwoo-kimm commented on src/test/java/game/domain/CarTest.java
> +    void Given_Name_When_newCar_Then_CarInstanceCreatedWithPositionZero() {
테스트 이름에서 given when then을 명시해주고 있고, 프로덕션 코드의 어떤 부분을 검증하는지 메서드 이름을 통해 정확히 알 수 있다는 점에서 제가 사용한 네이밍 규칙이 더 맘에 들었습니다!

현업에서는 보통 한글로 작성하나요??

2021-06-25 18:00 UTC, jiwoo-kimm commented on src/main/java/view/dto/ViewDto.java
> +//    public ViewDto(String carNamesInput, String raceCountInput) {
넵 롬복 적용 후에 검토를 꼼꼼하게 하지 않아서 실수했습니다😭

2021-06-25 18:04 UTC, jiwoo-kimm commented on src/main/java/view/dto/ViewDto.java
> +@Builder
같은 String 타입을 생성자 파라미터로 여러개 받기 때문에 오류 방지를 위해 빌더가 좋을 것이라 생각했습니다..만, 확인해보니 `ViewDto` 빌더를 사용하지 않고 객체를 생성하도록 작성해놨네요😭 빌더를 사용하도록 수정했습니다!

2021-06-26 01:07 UTC, jiwoo-kimm commented on build.gradle
> +sourceCompatibility = 11
네 repeat 메소드 사용을 위해 11버전을 적용했습니다! repeat 메서드는 별도로 작성하는 방향으로 수정했습니다

2021-06-27 07:09 UTC, jiwoo-kimm commented on src/main/java/game/util/CarNameParser.java
> +public class CarNameParser {
넵 parser는 유틸에 그대로 유지하고 validator을 별도로 분리해서 로직을 담당하도록 수정했습니다!

2021-06-27 08:39 UTC, jiwoo-kimm commented on src/main/java/view/OutputView.java
> +    public void printWinners(List<Car> winners) {
넵 `Winner` 도메인을 생성해서 로직을 옮기고 수정했습니다!

2021-06-27 08:40 UTC, jiwoo-kimm commented on src/main/java/game/util/RandomPick.java
> +    public static boolean isMove() {
옙 `RandomPick`을 `RandomUtil`로 변경하고 유틸와 도메인 로직을 분리했습니다.
테스트 관련해서는 어제 모임 시간에 우빈선생님이 보여주신 예시를 참고해서 다시 코드를 작성했습니다..!

2021-06-27 08:43 UTC, jiwoo-kimm commented on src/main/java/game/domain/Car.java
> +    private int position;
`position`은 항상 변하는 값이기 때문에, 불변객체로 `Car`을 설정하면 값이 바뀔 때마다 새로운 객체를 생성해야 한다는 문제가 생길 것 같아서 `final` 없이 하고, `name`에는 `final`을 붙였습니다.
그리고 `Candidate`, `Winner` 도메인을 새로 만들어서 `List<Car>`를  내부적으로 `unmodifiableList`로 가지고 있도록 했습니다!

2021-06-27 12:34 UTC, KIMSIYOUNG requested changes
지우님 너무 잘 반영해주셨네요! 반영하신 내용 확인했습니다🙂

추가로 고민하면 좋을 것들이 몇가지 있어서 리뷰 남겼습니다!

확인해주세요!

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/RandomStrategyImpl.java
> +public class RandomStrategyImpl implements RandomStrategy {
전략패턴 사용 👏 

[요런 방법 ](https://velog.io/@kyle/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EA%B0%80%EB%8A%A5%ED%95%9C-%EA%B5%AC%EC%A1%B0-%EB%A7%8C%EB%93%A4%EA%B8%B0)도 있으니 참고 부탁드려용!

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    public boolean isNewWinner(int maxPosition) {
메소드 분리 👏

자동차의 입장에서, `isNewWinner`와 `isGreaterThan` 중 어떤게 더 적절할까요?

전체 로직을 실행하는 과정에서 `isNewWinner`, `isAdditionalWinner` 는 매우 자연스러운 메소드이지만, 조금 덜 종속적인 의미로 사용할 수 있지 않을까요? `isGreaterThan`, `isSamePosition`

전체 도메인의 관점에서는 정확한 메소드 네임이지만 자동차 객체 자체에게는 스스로 저런 인터페이스를 열어주기에는 정보가 부족한 것 같아요.

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    public void moveForward() {
세부적인 부분도 메소드 분리를 통해 가독성이 좋네요👏

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +public class CarNameParser {
Validator를 사용한 유효성 검증 👏

도메인에서 검증 (자동차를 생성할 때, 이름의 길이가 1-5자가 아니라면 예외)  하는 것과, Validator에서 검증하는 것은 어떤 차이가 있을까요?

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/util/RaceCountParser.java
> +        if (!Pattern.matches(NUMBER_REGEX, inputLine))
요기도 중괄호 부탁드릴게요🙂

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/view/dto/ViewDto.java
> +@Builder
`같은 String 타입을 생성자 파라미터로 여러개 받기 때문에 오류 방지를 위해 빌더를 쓰는 게 더 좋을 것이라 생각했습니다` 

좋은 생각인 것 같습니다🙂

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/test/java/game/domain/CarTest.java
> +    void Given_Name_When_newCar_Then_CarInstanceCreatedWithPositionZero() {
저희팀은 한글로 작성하고 있는데, 컨벤션은 느끼는거에 따라 다르기 때문에 편하신대로 사용하시면 될 것 같습니다🙂

컨벤션은 결국 서로에게 가독성 좋고, 편리한 것으로 맞춰가기 위한 과정이니까 지우님이 말씀 주신 것처럼 `지우님만의 이유가 명확하게 있으면` 같이 협업하는 사람과 논의후에 편한걸로 사용하시면 될 것 같아요🙏 개인적인 생각으론 위와 같은 이름의 경우 테스트하는 내용이 복잡해지는 경우 가독성이 안 좋아질 수 있고, 사용하는 도메인 용어가 조금 다르다면 더 어렵게 느껴질 수 있겠죠?(한글에 비해서)

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/test/java/game/util/CarNameParserTest.java
> +    void Given_EmptyInputLine_When_parseCarNames_Then_RuntimeExceptionThrown() {
테스트는 `프로그램에 대한 문서` 의 역할도 한다고 생각해요🙂 

빈칸이 여러개인 경우에 대한 케이스를 테스트로 추가하면서 지우님이 생각한 의도를 보는사람도 명확하게 읽을 수 있게 되었네요!👏

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/test/java/game/domain/CandidateTest.java
> +        candidate.runOneRoundWith(() -> false);
람다를 잘 사용하셨네요 👏

람다를 통해 표현하는 것도 좋지만 `() -> false` 라는 키워드가  지우님의 의도를 명확하게 드러내고 있지 못하다는 생각이 드는데요!
부분적으로는 인터페이스/구현체(프로덕션에서) 사용하고 있고 테스트는 람다를 사용하니 조금 더 가독성이 안 좋은 것 같아요!

요 부분도 클래스로 나눠서 의미있는 이름을 지어주는게 어떨까요?

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/test/java/game/domain/CarTest.java
> +    void Given_NewCar_When_Move_Then_PositionOfCarIsOne() {
꼼꼼한 테스트👏

2021-06-27 12:34 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Candidate.java
> +    public String toString() {
모든 도메인에 전반적으로, 출력을 위해 toString을 View에 종속적인 형태로 가져가고 있는데요.

요 부분은 다음 2차 구현에서 어떤 형태로 도메인과/뷰를 분리하면 좋을지 생각해보아요!

2021-06-27 17:59 UTC, jiwoo-kimm commented on src/main/java/game/util/CarNameParser.java
> +public class CarNameParser {
Validator에서 먼저 검증을 하고 도메인으로 넘기면, 보다 빠른 시점에 예외를 발견할 수 있다는 점에서 더 좋을 것 같습니다. 하지만 `Car`이 불변객체가 아니다보니 필드값이 어느 순간 조건을 만족하지 않게 되더라도 추가로 검증하지 않는 한 버그가 발생한다는 문제가 있을 것 같아요..!
도메인을 생성할때 검증하면, 도메인이 그 필드가 유효한 범위를 내부적으로 알고 있다는 점에서 더 객체지향적인 것 같습니다. 그치만 여전히 값이 변한다는 문제와 발생할 것 같은데, `Car`을 불변객체로 만드는 게 가장 좋은 방식일까요?

2021-06-27 18:05 UTC, jiwoo-kimm commented on src/test/java/game/domain/CarTest.java
> +    void Given_Name_When_newCar_Then_CarInstanceCreatedWithPositionZero() {
오오 거의 모든 내용을 영어로 작성하니까 테스트 이름도 다 영어로 작성하는게 일반적일 줄 알았는데 꼭 그렇지만은 않은가 보네요! 다른 분들과도 같이 다양한 테스트를 쓰고 보면서 뭐가 더 편한지 고민하고 맞춰보겠습니다ㅎㅎ

2021-06-27 18:09 UTC, jiwoo-kimm commented on src/main/java/game/RandomStrategyImpl.java
> +public class RandomStrategyImpl implements RandomStrategy {
상속과 오버라이딩을 통해서 아예 랜덤 숫자를 부여할 수도 있네요!! 생각하지 못했는데 이번 기회에 알아두겠습니다ㅎㅎ

2021-06-27 18:12 UTC, jiwoo-kimm commented on src/main/java/game/domain/Car.java
> +    public boolean isNewWinner(int maxPosition) {
넵 의미를 분리해서 `isPositionGreaterThan`와 `isPositionSameWith`로 각각 메서드 이름 수정했습니다!

2021-06-27 18:13 UTC, jiwoo-kimm commented on src/main/java/game/util/RaceCountParser.java
> +        if (!Pattern.matches(NUMBER_REGEX, inputLine))
넵 수정했습니다!

2021-06-27 18:14 UTC, jiwoo-kimm commented on src/main/java/game/domain/Candidate.java
> +    public String toString() {
넵 더 고민하고 개선해보겠습니다!

2021-06-27 18:22 UTC, jiwoo-kimm commented on src/test/java/game/domain/CandidateTest.java
> +        candidate.runOneRoundWith(() -> false);
넵 `AlwaysMoveStrategy`와 `AlwaysNotMoveStrategy` 각각 클래스로 만들어서 테스트에 사용하도록 수정했습니다!

Functional Interface는 사실 저도 그냥 깜빡ㅋㅋㅋ한건데, 공식 문서 보니까 어노테이션 유무에 관계없이 작동한다고 하네요!

2021-06-28 03:14 UTC, KIMSIYOUNG commented on src/main/java/game/util/CarNameParser.java
> +public class CarNameParser {
`값이 변할 때 문제가 발생한다` 요 부분이 고민 포인트이신 것 같아요! 근데, 자동차객체가 불변이 아니더라도 자동차의 이름이 변경될 가능성이 있을까요? 현재 작성해주신 로직에서 보면 생성자와 동시에 초기화되고, 수정하는 메소드를 제공하고 있지 않은데 혹시 어떤 부분이 문제가 될 수 있는걸까요?

맞습니다, Validator에서 검증하는 것도 역할이 분리된 것 이지만 해당 로직은 `도메인에 가깝다`고 판단되고 해당 상태값을 알고 있는 도메인이 스스로 판단하여 생성을 못하도록 막음으로써 사용자는 `Validator` 라는 하나의 단계를 간과하더라도 도메인이 검증해주고 있고 로직 또한 분산되지 않아서 좋은 것 같습니다🙂

2021-06-28 03:17 UTC, KIMSIYOUNG approved these changes
지우선생님! 고생하셨습니다🙂

리뷰 반영하신 부분 확인했고, 머지하도록 할게요!

추가로 작성하신 부분에 궁금한 내용이 있는데 요건 디엠으로 여쭤볼게요!

2021-06-28 03:17 UTC, merged