[자동차 경주 게임] Step1 - 페어 프로그래밍
kiworkshop/java-racing-car pull request #5
Opened 2021-06-23 10:45 UTC by pageprologue

## 학습로그 
- git 히스토리 복제
  - https://pparkse2670.tistory.com/3
  - https://velog.io/@mook9288/git-0004

2021-06-24 13:51 UTC, wbluke requested changes
안녕하세요 희진 선생님~ 구현해주신 코드 잘 보았습니다 🙌 
몇 가지 코멘트 남겨보았는데요, 보시고 수정 후에 다시 태그 요청 부탁드립니다 ㅎㅎ
제가 질문 남긴 코멘트도 있는데 답변 달아주시면 좋을 것 같고요, 
하시다가 질문이 생기시면 코멘트에 남겨주시거나 DM 주세요~ 🙂

2021-06-24 13:51 UTC, wbluke commented on README.md
> +  - 우승자는 한 명 이상일 수 있음.
잘 정리해 주셨네요 👍

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/Car.java
> +    }
- 다음 시간에도 이야기를 하겠지만, 객체에 무분별한 setter를 열어두면 어떤 문제가 생길 수 있을까요?
- 특별히 setScore()는 Score를 set하는 setter 같지만, 실제로는 다른 역할을 수행하고 있네요 ㅎㅎ 의미를 더 드러내는 방식으로 메서드명을 수정해볼 수 있을까요? :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/Car.java
> +package com.mission2.racingcar;
패키지 이름은 실제 프로덕션 코드를 작성한다고 생각하고 명명해 보아요 ㅎㅎ
`com.mission2.racingcar` 대신 `racingcar`나 `game.racingcar` 등이 더 명확할 것 같아요 :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +     */
모든 메서드에 주석을 다는 것은 어쩌면 다른 사람에게 더 자세한 설명을 해줄 수 있다는 점에서 좋아보이지만,
반대로 메서드명의 역할인, `해당 객체가 수행하는 행위(책임)에 대한 설명`을 저해할 수 있는 여지가 되기도 합니다.
(메서드명으로 행위를 더 잘 드러내기를 고민하지 않고 한글 주석으로 풀어내버릴 수 있기 때문에)

따라서 주석은 전부 제거해주시고 메서드명에 더 집중해보시면 좋을 것 같아요 :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +    public static final String CAR_NAME_DELIMITER = ",";
중요한 상수들을 잘 분리해 주셨네요 👍

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        return (count > 0) ? false : true;
```suggestion
        return count <= 0;
```

요런 표현들이 많이 보이는데요, boolean return에서는 항상 simplify 를 고려하면 좋을 것 같아요 ㅎㅎ 다른 곳도 같이 확인해 주세요 :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +                .collect(Collectors.toList()));
Car 쪽에도 남긴 피드백인데요, setter 대신 생성자를 사용해서 한번에 초기화하면 어떨까요?
setter에 비해 생성자 초기화는 어떤 장점이 있을까요? :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            car.setScore(compareRandom(randomNumber));
`자동차가 1칸 전진한다` 라는 내용을 Car가 아닌 외부에서 값을 결정해서 넣어주고 있는데요.
Car가 score를 가지고 있으니 score를 증가시키는 책임은 Car에게 있으면 자연스럽지 않을까요? :)

2021-06-24 13:51 UTC, wbluke commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +public class CarRacingTests {
테스트를 열심히 작성해 주셨네요 👍

2021-06-24 13:51 UTC, wbluke commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +        String input = "AAA,BBB,CCC,DDD,EEE"; // Scanner 입력
이 친구가 테스트를 위한 데이터니 given절에 해당할 것 같네요 :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        return Arrays.stream(input.split(CAR_NAME_DELIMITER)).map(String::trim).toArray(String[]::new);
```suggestion
        return Arrays.stream(input.split(CAR_NAME_DELIMITER))
                .map(String::trim)
                .collect(Collectors.toList());
```

- stream 은 가독성을 위해 한줄에 하나씩 선언하는 것이 좋습니다 (다른 메서드도 같이 확인해 주세요 ㅎㅎ)
- Array보다 Collection API를 사용하는 것이 훨씬 이득인데요, 왜 그럴까요? :)

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +            throw new RuntimeException("잘못된 입력입니다.");
RuntimeException은 unchecked 예외의 가장 최상위 예외인데요,
항상 애플리케이션 단에서는 예외 발생 상황에 따라 `더 구체적인 (이미 Java 등에서 정의되어 있는) 하위 예외` 나 `custom 예외` 를 사용하는 것이 좋습니다.
ex) IllegalArgumentException, IllegalStateException

2021-06-24 13:51 UTC, wbluke commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        if (!Pattern.matches("^[0-9]*$", input)) {
정규식은 성능상 상당히 무거운 축에 속합니다.
꼭 필요한 경우가 아니라면 피하는 것이 좋은데요 ㅎㅎ
Integer.parseInt 변환 시 어떤 예외가 발생되는지 확인해보고, catch 해서 다시 원하는 다른 예외로 메시지와 함께 던지는 구조는 어떨까요? :)

2021-06-24 13:51 UTC, wbluke commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +        service.printWinner(winners);
요런 경우는 저번 시간에 말씀드렸듯이 assert문으로 검증하는 것이 아니라서, 올바른 테스트라고 할 수는 없을 것 같아요 ㅎㅎ
그래서 이런 UI에 관련된 로직은 테스트하기가 어렵습니다.
단, 이런 로직을 테스트하기를 포기하기보다, `어떻게 하면 조금이라도 테스트 가능한 영역을 넓히는 구조 개선을 진행할 수 있을까?` 에 대한 고민이 필요합니다 :)

2021-06-24 13:51 UTC, wbluke commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +        Race race = service.initRace(carNames, gameCount);
이 라인들도 다 given에 해당합니다 ㅎㅎ
when 절에는 정말 테스트하고자 하는 행위! 만 있어야 합니다 :)

2021-06-24 13:51 UTC, wbluke commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    void 자동차_이름_입력() {
요거는 그냥 사견인데요, DisplayName을 사용하고 있으니 메서드 이름은 그냥 영어로 지어도 좋을 것 같아요 :)

2021-06-25 08:50 UTC, h2jin1 commented on src/main/java/com/mission2/racingcar/Car.java
> +    }
중요한 지적 감사합니다! 
객체지향 원칙에서 객체의 정보는 은닉되어야 합니다. setter를 사용하면 파라미터를 검증할 수는 있으나, 데이터의 수정은 피할 수 없습니다. 객체의 상태가 보호되기 위해서는 생성자를 통해서만 객체를 생성하거나, builder 패턴을 사용할 수 있을 것 같습니다.

  - [Getter, Setter 지양하기](https://velog.io/@sezeom/Getter-Setter-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0)
          - 객체의 상태가 변경되는 것은 객체 스스로의 행동에 의해서야 한다.
 - [Setter 메소드](https://mititch.tistory.com/77)
- [불편 클래스](https://hyuntaeknote.tistory.com/5)
	  - 불변 클래스는 인스턴스의 값이 변하지 않기 때문에 상태 변화에 대해서 신경 쓰지 않아도 된다.

2021-06-25 08:57 UTC, h2jin1 commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    void 자동차_이름_입력() {
Junit4와 Junit5를 혼용해서 쓰고 있었네요~
- [Junit5 docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator)
- [Junit5 테스트 코드 작성법](https://dev-mb.tistory.com/292)
        - 테스트 코드를 작성할 때는 Snake 표기법으로 작성한다.

2021-06-25 08:59 UTC, pageprologue commented on src/main/java/com/mission2/racingcar/Car.java
> +    }
중요한 지적 감사합니다! 
객체지향 원칙에서 객체의 정보는 은닉되어야 합니다. setter를 사용하면 파라미터를 검증할 수는 있으나, 데이터의 수정은 피할 수 없습니다. 객체의 상태가 보호되기 위해서는 생성자를 통해서만 객체를 생성하거나, builder 패턴을 사용할 수 있을 것 같습니다.

  - [Getter, Setter 지양하기](https://velog.io/@sezeom/Getter-Setter-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0)
          - 객체의 상태가 변경되는 것은 객체 스스로의 행동에 의해서야 한다.
 - [Setter 메소드](https://mititch.tistory.com/77)
- [불편 클래스](https://hyuntaeknote.tistory.com/5)
	  - 불변 클래스는 인스턴스의 값이 변하지 않기 때문에 상태 변화에 대해서 신경 쓰지 않아도 된다.

2021-06-25 09:00 UTC, pageprologue commented on src/test/java/com/mission2/racingcar/CarRacingTests.java
> +    void 자동차_이름_입력() {
Junit4와 Junit5를 혼용해서 쓰고 있었네요~
- [Junit5 docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator)
- [Junit5 테스트 코드 작성법](https://dev-mb.tistory.com/292)
        - 테스트 코드를 작성할 때는 Snake 표기법으로 작성한다.

2021-06-26 15:12 UTC, pageprologue commented on src/main/java/com/mission2/racingcar/CarRacingService.java
> +        return Arrays.stream(input.split(CAR_NAME_DELIMITER)).map(String::trim).toArray(String[]::new);
저는 크기를 지정해야 메모리 성능에 좋다고 배웠는데요. 리스트가 사용하기는 편하지만 크기를 명확하게 알 수 있는 목록은 배열을 주로 사용했습니다. 그런데 여기서는 성능까지는 고려하지 않아도 될 것 같고, 배열보다 리스트의 장점이 더 많으니 잘 활용해봐야겠네요!

- [Array vs Collection API](https://stackoverflow.com/questions/6100148/collection-interface-vs-arrays/6105705)
  - Array는 초기화된 길이 변경이 불가능하고, null을 허용해야 하며, 스레드에 안전하지 않다. 
  - List는 초기화된 길이의 변경이 가능하고, 스레드로부터 안전하고, 다양한 Collection API를 제공한다.

- [Array vs ArrayList](https://velog.io/@humblechoi/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-Array-vs-ArrayList)
  - ArrayList 의 기본 생성 길이는 10 이다. element를 add 할 때 capacity가 배열의 길이와 같아지면 기존용량 + 기존용량/2 만큼 크기가 늘어난 배열에 기존의 배열을 copy해 준다.
  - ArrayList의 자동 크기 조정은 임시 배열을 사용하여 이전 배열의 요소를 새 배열로 복사하기 때문에 성능이 저하된다.
  - ArrayList는 Generics(제네릭스)를 통해 Type-Safety를 보장한다.

2021-06-27 12:27 UTC, wbluke approved these changes
피드백 반영 잘 해주셨네요! 👍 감사합니다 ㅎㅎ
몇 가지 추가 코멘트를 더 남겼는데요, 다음 단계 리팩토링 미션 진행하시면서 같이 반영해보면 좋을 것 같아요 🙂

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacing.java
> +            String message = "자동차 이름을 다시 입력해 주세요. (공백 또는 " + CarRacingService.MAX_CAR_NAME_COUNT + "자 초과)";
String.format() 을 사용하면 어떤 메시지인지 가독성에 더 좋을 것 같아요 ㅎㅎ
다른 String 메시지도 한번 같이 체크해보면 좋겠어요 :)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +    }
앞으로 우리가 `domain` 이라고 부르는 객체들에 핵심 비즈니스 로직을 넣는 연습을 해보게 될텐데요 ㅎㅎ
`자동차의 이름 길이는 5 이하이다` 라는 요구사항에 대한 validation은 자동차 객체에서 해보면 어떨까요?
Service에서는 입력 받은 자동차 이름을 자동차로 변환하는 역할만 가져가고, 
실제로 변환하면서의 validation은 name 필드를 가지고 있는 Car 객체에서 담당하는거죠.
이렇게 되면 도메인 객체인 Car에 유의미한 로직이 들어가게 되고, 객체가 더 풍성해지고 책임이 명확한 객체로 동작하게 되며, 단위 테스트도 가능해집니다.

한번 리팩토링 및 테스트 추가를 진행해 보시고 전후 어떤 차이점이 있는지 비교해 보세요 :)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +    }
Race 객체를 만드셨군요! 좋습니다 👍 
자, 위에 Car validation 관련해서도 피드백 남겼지만, 객체가 존재하고 getter만 있는 객체는 큰 의미를 둘 수 없다고 생각해요.
(데이터를 묶어서 이름을 부여했다는 측면에서는 의미가 아예 없는 것이 아니지만)

우리가 설계하는 이 객체라는 것은 각자 객체가 담당한 역할과 책임을 수행해야 하며, 이를 외부에 메서드 API 형태로 제공함으로써 객체들이 서로 협력할 수 있도록 하는 것이 좋은 설계인데요.
`racing(race);` 대신 `race.proceed();` 와 같은 형태는 어떨까요? (메서드 이름은 원하는대로 해주세요 ㅎㅎ 예시입니다)

메서드 형태를 비교해볼까요?
전자의 표현에서는 Race라는 객체가 존재하지만, 외부(Service)에서 해당 객체를 가지고 조작을 해주어야지만 `레이싱 진행`이라는 비즈니스 로직을 풀어낼 수가 있다고 보여지고,
후자의 표현에서는 Race라는 객체가 능동적으로 자신이 가지고 있는 데이터를 활용하여 `레이싱 진행`이라는 책임을 다하고 있는 것으로 보입니다.
전자처럼 설계를 하게 되면 결국 지금 사용하신 `race.getCars()`라는 표현과 같이 Race라는 자체적인 객체가 있음에도 불구하고 불필요하게 `cars`라는 데이터를 getter로 꺼내서 비즈니스 로직을 수행할 수밖에 없습니다.

코멘트를 조금 길게 작성해 보았는데요, 요런 객체지향에 관련된 이야기는 매 모임 시간마다 언급할 예정이니, 계속 들어보면서 곱씹어보고 코드로 작성해보면서 익숙해져보면 좋을 것 같습니다! :)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +    public static final int MAX_CAR_NAME_COUNT = 5;
상수들도 이제 존재에 맞게 각 객체로 분리해보면 좋을 것 같아요.
어떤 상수는 지금처럼 Service에 있는 게 어울리는 상수도 있을 것이고,
어떤 상수는 특정 객체에 있는 것이 어울릴 수도 있을겁니다.
그리고 해당 상수를 외부에서 사용하는지 유무에 따라 접근제어자도 public/private으로 구분해보면 좋을 것 같아요 :)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +        return Arrays.asList(input.split(CAR_NAME_DELIMITER));
> 저는 크기를 지정해야 메모리 성능에 좋다고 배웠는데요. 리스트가 사용하기는 편하지만 크기를 명확하게 알 수 있는 목록은 배열을 주로 사용했습니다. 그런데 여기서는 성능까지는 고려하지 않아도 될 것 같고, 배열보다 리스트의 장점이 더 많으니 잘 활용해봐야겠네요!

맞습니다, 원래라면 성능을 고려할 경우 말씀하신대로 크기를 지정해서 사용하는 것이 좋은데요.
제 생각을 말씀드리자면, 하드웨어가 지금처럼 발전하지 않았고 정말 1비트의 메모리도 아껴서 프로그래밍을 해야 했던 호랑이 담배피던 시절에는 배열을 사용하는 것이 더 맞았을거에요.
하지만 지금 시대에는 애플리케이션 수준에서 배열 VS. 리스트 와 같은 관점을 가지고 메모리 성능을 생각하지 않아도 될 정도로 하드웨어가 성대한 발전을 했기 때문에, 지금은 특별한 목적이 있지 않는 이상 무조건 활용성이 높은 리스트, 컬렉션 API를 사용하는 것이 이득이라고 봅니다.
(가전제품과 같은 곳에 사용되는 경량화된 임베디드 같은 경우는 지금도 당연히 비트 단위 고려가 필요할거에요 ㅎㅎ)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +                .getAsInt();
메서드로 추출해볼 수 있겠네요 :)

2021-06-27 12:27 UTC, wbluke commented on src/main/java/game/racingcar/CarRacingService.java
> +    }
다음 단계가 MVC 구조로 분리하기 미션인데요, 이제 요런 출력 로직들을 별도의 객체로 분리해보면 좋을 것 같아요 :)

2021-06-27 12:27 UTC, merged