[자동차 경주 게임] Step 2 리뷰 요청드립니다
kiworkshop/java-racing-car pull request #7
Opened 2021-07-01 16:13 UTC by jiwoo-kimm

안녕하세요!
자동차 경주 게임 Step 2 과제 제출합니다.

상세 내용과 몇 가지 질문은 리드미와 스터디로그에 작성했습니다.
리뷰 부탁드립니다! 😃

2021-07-03 06:19 UTC, KIMSIYOUNG requested changes
지우선생님 안녕하세요.  MVC 구조로 잘 분리해주셨네요 👏

고민하고 있으신 내용에 대해서는 제가 제대로 이해한지 모르겠네요. 제 생각 추가해두었으니 읽어보시고 편하게 DM/댓글 주세요! 

많은 고민을 하면서 개발하고 계신게 느껴지네요. 멋있습니다 👏🙂

2021-07-03 06:19 UTC, KIMSIYOUNG commented on README.md
> +- [x] `Candidate` 대신 `Race`에 `List<Car>` 필드로 갖고 관리하기
구체적인 기능목록 + 구현 완료 표시 좋네요👏

2021-07-03 06:19 UTC, KIMSIYOUNG commented on STUDYLOG.md
> +그런데 이렇게 하면, `runOneRoundWith(MoveStrategy strategy)`에서 파라미터가 필요없게 되고, `MoveStrategy`에 따라 테스트를 할 수 없는 상황이 됩니다. 그렇다고 파라미터를 그대로 유지하자니, 메서드를 호출할 때마다 `MoveStrategy` 객체를 참조하는 것이 깔끔가지 않은 것 같습니다.
지우선생님 안녕하세요. 1번 질문의 의미는 항상 동일한 `MoveStrategy` 를 사용하는데, 이를 Race가 직접적으로 가지면 테스트가 어렵고 그렇다고 파라미터로 넘기자니 늘 동일한 값인데 그럴 필요가 있을까? 라는 의미로 이해하면 될까요?

지우선생님 말씀대로 프로덕션 코드에서는 항상 하나의 전략을 사용하기에 유의미한가? 라는 고민은 매우 좋은 것 같습니다👏 이에 대해 저의 개인적인 생각은, 유의미하다고 할 수 있는 것 같습니다. 해당 메소드를 테스트 할 수 있는 방법은 아래와 같이 여러개가 있을 수 있는데요. 그 중 프로그램 요구사항을 만족하며 `자동차가 움직이는 방법이 달라졌을 때` 가장 유연한 방법은 무엇일까요? 저는 해당 의문에 대한 답이 전략패턴을 사용하는 것이라고 생각하기에 현재의 방법은 좋은 것 같습니다.
- 파라미터로 랜덤한 값을 받기
- 상속을 통한 테스트
- 현재와 같은  전략패턴

2. GameController에서 항상 고정된 값을 선언하는게 싫다면 전략 또한 사용자에게 입력 받는 건 어떨까요? 요구사항을 벗어나는 기능이지만 고민해보면 좋을 것 같아요. 플로우는 아래와 같겠네요. 
- 사용자는 경주에 사용할 전략을 입력한다. (예를 들어 랜덤전략/이름전략(이름으로 가산점을 주는)/...)
- Controller는 입력값을 기반으로 MoveStrategy중 어떤 전략을 사용할 지 찾아온다.
- 이를 Race에서 사용하게 게임을 진행한다.

2021-07-03 06:19 UTC, KIMSIYOUNG commented on STUDYLOG.md
> +`isRunning()` 메서드가 올바른 bool 값을 리턴하는지 테스트하고 싶은데, 그러려면 `currentRoundCount`의 접근자를 더 공개적으로 바꾸던가 메서드를 추가해야 돼서 테스트를 하지 않았습니다. 이전 1차 미션 때 테스트를 위한 프로덕션 코드의 변경은 지양해야 한다고 느꼈기 때문인데요.. 다른 좋은 방법이 떠오르지 않아서 코드를 이 상
해당 메소드는 `runWith`를 사용하여 테스트 할 수 있다고 생각이 되는데요. 지우선생님은 해당 메소드만 단독으로 테스트하고 싶으신걸까요?

2021-07-03 06:19 UTC, KIMSIYOUNG commented on STUDYLOG.md
> +현재는 예외를 던질 때 필요한 정보값이 없고 메세지만 넘겨 주면 된다고 생각해서 `ExceptionMessage`만 인자로 넘기도록 했습니다. 그런데 현업에서는 로깅도 해야 하니 더 개선된 방식으로 예외를 처리할 것 같은데, 이에 관한 정보를 찾기 어려웠습니다. 혹시 예외처리 관련해서 참고하고 공부할 만한 자료가 있다면 추천 부탁드립니다..!
예외처리와 로그는 항상 어려운 것 같습니다. [이 분](https://www.slideshare.net/dhrim/ss-2804901)이 잘 정리해주신 것 같긴한데, 상황에 따라 어떻게 사용할지는 본인이 결정해야할 것 같습니다.

예외 메시지도 일관되게 확인할 수 있도록 Enum으로 분리해서 관리하는 부분 👏 

다만 요번 미션에서 자동차와 레이스간의 예외들이 조금 막연하게 사용되고 있는 것 같습니다. RuntimeException보단 하위 타입을 사용하는 걸 권장하고, RuntimeException을 터트리는데 Exception을 던지고 있어요! 아래의 키워드로 예외에 대해 조금 더 공부해보아요
- checked Exception
- unChecked Exception
- 예외 상속 구조
- custom exception

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/game/controller/GameController.java
> +            View.printOneRoundResult(OneRoundResultDto.builder()
View에 도메인을 노출하지 않고 DTO를 사용하신 부분 👏

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/util/CarNameParser.java
>      public static List<String> parseCarNames(String inputLine) throws RuntimeException {
[1차 리뷰 중 요부분에 대해서 누락하신 것 같아요 ](https://github.com/kiworkshop/java-racing-car/pull/4#discussion_r659312908) 읽어보시고 한 번 고민해보세요🙂

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/game/view/dto/WinnerDto.java
> +    @Getter
요기서는 Collections.unmodifiableList를 사용하지 않는 이유가 있을까요?

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/game/controller/GameController.java
> +        while (race.isRunning()) {
MVC구조의 분리 👏 

현재는 비즈니스 로직이 단순한데요. 비즈니스 로직이 복잡해지면 `Controller` 가 많은 역할을 담당하고 있기 때문에 무거워질 것 같아요. (지금도 프로그래밍 요구사항 10줄이 넘네요!) 

만약 요구사항이 복잡해진다면 현재 컨트롤러에 있는 로직중 어떤 부분이 어디로 빠지면 좋을지 고민해보고 말씀 부탁드립니다🙂

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Car.java
> +    private void validate(String name) throws Exception {
위에서 말씀 드린 예외에 대한 공부는 이런 `throws Exception이 맞는가` 에 대한 스스로의 확신을 가질 수 있으시다면 충분합니다🙂 

처음 접할 땐 조금 어려울 수 있는데, 어려운 부분이 있다면 편하게 디엠주세용

2021-07-03 06:19 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
리뷰라기보단, 저도 요 미션을 예전에 하면서 고민했던 부분이 있는데요. `Collections.unmodifiableList`가 불변을 보장할까요? 고민해보시고 [이 글을 보면서](https://velog.io/@kyle/%EB%B6%88%EB%B3%80-%EA%B0%9D%EC%B2%B4%EB%9E%80-Java-Immutable-Object) 잘 아시겠지만 한 번 더 정리해보시면 좋을 것 같습니다.

2021-07-07 00:21 UTC, jiwoo-kimm commented on STUDYLOG.md
> +그런데 이렇게 하면, `runOneRoundWith(MoveStrategy strategy)`에서 파라미터가 필요없게 되고, `MoveStrategy`에 따라 테스트를 할 수 없는 상황이 됩니다. 그렇다고 파라미터를 그대로 유지하자니, 메서드를 호출할 때마다 `MoveStrategy` 객체를 참조하는 것이 깔끔가지 않은 것 같습니다.
네네! 전략패턴이 가장 유연하게 규칙 변동에 대해 대응할 수 있는 방법인 것 같아요. 고정된 값이 아니라 입력을 받게 되더라도, 값 입력받아서 주입하는 부분만 수정하고, 나머지 로직은 그대로 유지하면 되네요..! 지금은 하나의 규칙만 있으니 의문이 들었었는데, 말씀 들으니 납득이 됐습니다. 😄

2021-07-07 00:26 UTC, jiwoo-kimm commented on STUDYLOG.md
> +`isRunning()` 메서드가 올바른 bool 값을 리턴하는지 테스트하고 싶은데, 그러려면 `currentRoundCount`의 접근자를 더 공개적으로 바꾸던가 메서드를 추가해야 돼서 테스트를 하지 않았습니다. 이전 1차 미션 때 테스트를 위한 프로덕션 코드의 변경은 지양해야 한다고 느꼈기 때문인데요.. 다른 좋은 방법이 떠오르지 않아서 코드를 이 상
음 `currentRoundCount`만큼 라운드가 수행이 잘 되는지를 확인하고 싶었어요. 그러려면 `isRunning()`에서 bool 값을 잘 리턴하는지만 확인하면 된다고 생각했고요!

`runWith()`를 사용하여 테스트한다면, `targetRoundCount`만큼 `AlwaysMoveStrategy`로 `runWith()`를 실행하고, 자동차의 `position`이 `targetRoundCount`와 같은지 검증하는 방식으로 진행하면 될까요?

2021-07-07 00:35 UTC, jiwoo-kimm commented on STUDYLOG.md
> +현재는 예외를 던질 때 필요한 정보값이 없고 메세지만 넘겨 주면 된다고 생각해서 `ExceptionMessage`만 인자로 넘기도록 했습니다. 그런데 현업에서는 로깅도 해야 하니 더 개선된 방식으로 예외를 처리할 것 같은데, 이에 관한 정보를 찾기 어려웠습니다. 혹시 예외처리 관련해서 참고하고 공부할 만한 자료가 있다면 추천 부탁드립니다..!
넵 자료 감사합니다. 구체적 Exception 타입을 사용하고 메시지를 정확하게 남기는 게 중요해보이네요! 더 공부해보겠습니닷

2021-07-07 00:38 UTC, jiwoo-kimm commented on src/main/java/util/CarNameParser.java
>      public static List<String> parseCarNames(String inputLine) throws RuntimeException {
Validator 뿐 아니라 Parser도 별도로 구현하기보다는 도메인 안에서 하는 게 더 안전하다는 말씀이신가요? 혹시 그럼 `Cars`라는 도메인을 추가로 만들어서 그 안에서 `List<Car>`를 저장하고 이름도 파싱하게 만드는 방식으로 리팩토링하는 건 어떨까요??

2021-07-07 00:39 UTC, jiwoo-kimm commented on src/main/java/game/view/dto/WinnerDto.java
> +    @Getter
아뇨 이유는 없는데, 아직 익숙하지 않아 깜빡한 것 같습니다! 수정하겠습니다

2021-07-07 00:57 UTC, jiwoo-kimm commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
넵 꼼꼼히 읽고 이해했습니다!

제가 작성한 코드에서는 `generateCarList()` 리턴값이 외부에서 접근 불가능할 뿐 아니라 `Collections.unmodifiableList`가 되었으니,`cars`는 불변리스트이고 `Race`는 불변객체인게 맞나요?

2021-07-10 06:24 UTC, KIMSIYOUNG commented on STUDYLOG.md
> +`isRunning()` 메서드가 올바른 bool 값을 리턴하는지 테스트하고 싶은데, 그러려면 `currentRoundCount`의 접근자를 더 공개적으로 바꾸던가 메서드를 추가해야 돼서 테스트를 하지 않았습니다. 이전 1차 미션 때 테스트를 위한 프로덕션 코드의 변경은 지양해야 한다고 느꼈기 때문인데요.. 다른 좋은 방법이 떠오르지 않아서 코드를 이 상
해당 메소드만으로 판단할 수 있다면 좋지만, 해당 객체의 정보를 통해서 판단할 수 있는 것만으로 충분한 것 같아요. (외부 객체에 의존하지 않고) 

모든 메소드를 단독으로 테스트 가능한 형태로 만드는건 사실상 조금 어렵지 않나, 라고 생각해서 위 같이 말씀드렸습니다🙂

2021-07-10 06:26 UTC, KIMSIYOUNG commented on src/main/java/util/CarNameParser.java
>      public static List<String> parseCarNames(String inputLine) throws RuntimeException {
좋은 방법인 것 같습니다🙂

도메인에서 Parser를 부르는게 어떤가 라는 생각도 들구요 `,` 를 기준으로 구분하는 것도 도메인 로직이라고 생각이 되어서 말씀드렸습니다🙂 

Cars라는 도메인을 사용하는 것도 좋을 것 같아요

2021-07-10 06:29 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
네네, 맞습니다. 

다만 제가 의도했던 것은 Race를 생성하는 곳에서 사용한 List<String> carNames의 값을 변경한다면 내부값도 변경된다는 말이였어요! 그래서 의도한 내용은 Collections.unmodifiableList도 좋지만, 생성자에서 입력된 리스트를 새로운 리스트로 만들어서, 가지고 있다면 Race를 생성한 곳에서도 생성이후 Race를 변경할 수 없다는 것이였습니당! 

현재 구조에서는 다른곳에서 이를 사용하지 않기 떄문에 관계없지만 지우선생님이 작성하신 코드로 Race를 누군가 사용한다면 문제가 될 수도 있겠죠? (사실 이렇게까지는 아니겠지만, 정말 불변인가? 라는 고민을 해보는게 좋을 것 같아서 코멘트 드렸습니다)

2021-07-12 04:45 UTC, jiwoo-kimm commented on STUDYLOG.md
> +`isRunning()` 메서드가 올바른 bool 값을 리턴하는지 테스트하고 싶은데, 그러려면 `currentRoundCount`의 접근자를 더 공개적으로 바꾸던가 메서드를 추가해야 돼서 테스트를 하지 않았습니다. 이전 1차 미션 때 테스트를 위한 프로덕션 코드의 변경은 지양해야 한다고 느꼈기 때문인데요.. 다른 좋은 방법이 떠오르지 않아서 코드를 이 상
아 넵 알겠습니다! 🙂

2021-07-12 09:22 UTC, jiwoo-kimm commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
아 이해했습니다! 불변객체에 신경써서 리팩토링 진행했습니다 확인 부탁드려요!

2021-07-12 09:24 UTC, jiwoo-kimm commented on src/main/java/game/controller/GameController.java
> +        while (race.isRunning()) {
`Controller`는 `View`와 `Race` 간의 로직 흐름만 관리하고, 실제 비즈니스 로직은 도메인 안에서 실행하도록 리팩토링해봤습니다. 😃 
여전히 `Race` 객체의 책임이 다른 객체들보다 무거운 것 같은데, 코드 자체는 클린 코드에서 요구하는 수준으로 한 눈에 들어오는 것 같습니다...! 이 정도면 괜찮을까요!?

2021-07-12 09:25 UTC, jiwoo-kimm commented on src/main/java/util/CarNameParser.java
>      public static List<String> parseCarNames(String inputLine) throws RuntimeException {
옙 도메인을 추가해서 구현했습니다!

2021-07-16 15:52 UTC, KIMSIYOUNG commented on src/main/java/game/controller/GameController.java
> +        while (race.isRunning()) {
네네, 지우선생님

말씀하신대로 비즈니스 로직의 흐름을 관리하는 Race와, 해당 Race 그리고, View와 소통하는 Controller로의 분리를 의도한 것이 맞고 잘해주신 것 같습니다🙂

추후에 웹에서는 Race가 일반적으로 Service 계층의 역할을 하신다고 보시면 될 것 같아요.

2021-07-16 15:54 UTC, KIMSIYOUNG commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
넵넵! 지우선생님 확인했습니다🙂

잘 작성해주신 것 처럼, 생성자에서 해당 값을 초기화시킨다면 외부에서도 해당 값을 제어할 수 없겠죠? 또한 지우선생님이 작성해주신대로, 생성과 동시에 `Collections.unmodifiableList` 를 사용한다면 내부에서도 값을 추가하거나, 제어할 수 없다는 의도가 잘 드러나는 것 같습니다.

2021-07-16 16:05 UTC, KIMSIYOUNG approved these changes
지우선생님, 확인이 늦어 죄송합니다. 댓글 주신 부분은 대댓글로 달아두었어요!

제가 의도했던 코멘트대로 잘 수정해주신 것 같아요. 그리고 로또하면서 학습하신 일급컬렉션도 적용하면서 더 리팩토링하신 부분도 좋습니다👏

한가지 조금 더 고민해보면 좋을 부분은, Exception을 Illegal로 변경한거는 좋은데요. 해당 예외를 아무곳에서도 잡아서 처리하는 부분이 없음에도 불구하고 모든 메소드에서 throws IllegalArgumentException을 던지고 있습니다. 요 부분 이렇게 작성하신 의도만 같이 얘기해보면 좋을 것 같습니다. 미션은 머지할게요!

고생하셨습니다. 최고에요👏🤭

2021-07-16 16:05 UTC, merged

2021-07-17 08:26 UTC, jiwoo-kimm commented on src/main/java/game/controller/GameController.java
> +        while (race.isRunning()) {
넵! 감사합니다

2021-07-17 08:28 UTC, jiwoo-kimm commented on src/main/java/game/domain/Race.java
> +        cars = Collections.unmodifiableList(generateCarList(carNames));
넵!! 앞으로도 잘 생각하고 적용해보도록 하겠습니다