Step2 - 자동차 경주 MVC
kiworkshop/java-racing-car pull request #8
Opened 2021-07-02 02:48 UTC by pageprologue

### 학습로그
- Fork 한 저장소에 최신 소스를 가져온다.
[Upstream](https://coding-groot.tistory.com/80)

2021-07-04 02:39 UTC, wbluke requested changes
희진 선생님~ 상당히 깔끔하게 MVC 구조를 적용해 주셨네요 ㅎㅎ 👍 
조금 더 다듬을 수 있는 부분이 있어서 코멘트 남겼습니다 !
확인해보시고 수정 후 재요청 부탁드려요~ 🙂 
(질문 있으시면 언제든 DM이나 코멘트 남겨주세요 ㅎㅎ)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/view/InputView.java
> +public class InputView {
사용자 입력의 책임을 InputView로 잘 분리해 주셨네요 👍 
정적 클래스는 인스턴스 생성을 방지하기 위해 방어 로직으로 private 생성자를 두는 것이 좋습니다 :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/view/InputView.java
> +        while (!Car.isValidCarName(input)) {
MVC 모델의 핵심 중 하나는 View 와 Model의 분리인데요, 
현재 사용자 입력이 올바르지 않은 경우 재입력을 받도록 하기 위해 loop 로직이 InputView에 있어서 
View가 Model을 참조할 수밖에 없는 구조인 것 같아요.
View와 Model이 서로 의존 관계를 가지게 되면 Model의 변경에 따라 View도 영향을 받을 수밖에 없습니다 ㅎㅎ

InputView에서는 정말 최소한의 입력에 대한 역할만 가지도록 하고, 그 외 처리에 관련된 것들은 Controller에서 해보면 어떨까요? :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/view/InputView.java
> +        while (!Race.isValidGameCount(input)) {
그리고 자동차 이름과 레이스 횟수에 대해서 validation을 하고 있지만, validation의 수가 늘어나면 해당 로직도 여러모로 변경이 심할 것 같아요. (예외 메시지도 현재 1개의 validation에 대한 내용이네요)
요거 관련해서는 Model 쪽에 조금 더 피드백 남길게요 :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/domain/Car.java
> +    }
OOP에서 정적 메서드는 기본적으로 안티 패턴입니다. (꼭 필요한 경우에만 사용하는 것이 좋아요)
잘 살펴보면, `어떤 String input을 받아서 ',' 라는 구분자로 구분한 뒤 이름 길이를 validation 하는 것` 이라는 책임이 Car 라는 객체와 어울리는지 의문을 제기해볼 수 있습니다 ㅎㅎ
위 책임을 잘개 쪼개보면,
- 어떤 String input 을 받아서
  - Car 입장에서는 이 String이 어떤 String인지 알 수도 없고, 알 필요도 없을 것 같아요.
- ','라는 구분자로 구분한 뒤
  - ','로 이름을 구분한다는 내용은 Car에서 알 필요가 없고, 오히려 InputView에서 관리하는 게 맞지 않을까 싶어요 ㅎㅎ (요구사항이 달라져서 구분자가 변경된다면?)
- 이름 길이를 validation 하는 것
  - Car를 생성할 때 체크한 뒤 예외를 던지는 쪽이 맞지 않을까 해요. 생성자의 역할 중 하나는 올바른 인스턴스를 할 수 있는지 validation 하는 것도 있거든요.

```java
public Car(String name) {
    if (name == null || name.length > 5) {
        throw new IllegalArgumentException("예외 메시지");
    }

    this.name = name;
    this.score = 0;
}
```

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/domain/Race.java
> +    public static final int MAX_GAME_COUNT = 10;
이 부분은 요구사항에 없었는데 임의로 추가하신 부분일까요~? :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/domain/Car.java
> +    }
Race 쪽에 있는 static validation 메서드도 마찬가지로 Race 자체의 객체 역할에 대해서 고민해 본 뒤 더 적절한 곳으로 이동해보면 좋을 것 같아요 :)

2021-07-04 02:39 UTC, wbluke commented on src/test/java/game/racingcar/RacingCarTest.java
>  package game.racingcar;
각 단위 테스트는 프로덕션 객체의 패키지와 동일해야 하고, 클래스 이름도 동일해야 합니다 ㅎㅎ
예를 들면, 다음과 같아요.
`game.racingcar.domain.Car` -> `game.racingcar.domain.CarTest`
`game.racingcar.domain.Race` -> `game.racingcar.domain.RaceTest`

2021-07-04 02:39 UTC, wbluke commented on src/test/java/game/racingcar/RacingCarTest.java
> +        boolean isValid = Race.isValidGameCount(gameCount);
위에도 비슷한 코멘트 남겼는데요, Race에 대한 단위 테스트는 RaceTest로 만들어서 작성해 보아요 :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/domain/Race.java
> +    }
모임 시간에 진행했던 전략 패턴을 적용해보면 어떨까요?
랜덤 관련 로직을 별도로 뽑고, 외부로 분리해낸다면 단위 테스트가 가능한 영역이 늘어나고 의미도 더 명확해질 거에요 ㅎㅎ
Race 객체에 대한 책임도 어느 정도 분리가 될 것 같고요 :)

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/view/OutputView.java
> +public class OutputView {
출력 로직도 책임에 따라 잘 분리해 주셨네요 👍

2021-07-04 02:39 UTC, wbluke commented on src/main/java/game/racingcar/view/OutputView.java
> +        System.out.println(String.join(", ", winners) + "가 최종 우승했습니다.");
`", "` 이 부분도 요구사항에 따라 변경될 수 있는 `매직스트링`이기 때문에 상수로 관리되면 좋을 것 같네요 :)

2021-07-04 02:39 UTC, wbluke commented on src/test/java/game/racingcar/RacingCarTest.java
> +        List<String> carNames = Arrays.asList(input.split(","));
이 부분은 테스트를 위한 데이터를 준비하는 과정이니 given절로 보는 것이 맞습니다.
보통 when절의 경우 테스트하고자 하는 행위 1줄인 경우가 많아요 :)

2021-07-06 11:14 UTC, pageprologue commented on src/main/java/game/racingcar/domain/Race.java
> +    public static final int MAX_GAME_COUNT = 10;
네 이 부분은 제가 추가로 개발한 부분인데요. 
다시 리팩토링 하면서 요구 사항대로 기능을 구현해보기 위해 삭제하였습니다.

2021-07-06 11:15 UTC, pageprologue commented on src/test/java/game/racingcar/RacingCarTest.java
>  package game.racingcar;
네 알겠습니다 :)

2021-07-09 00:31 UTC, wbluke approved these changes
주중에 너무 바빠서 확인이 조금 늦었네요ㅠㅠㅎㅎ
리팩토링 하신 부분과 테스트 추가해주신 부분 잘 보았습니다! 👍 
몇 가지 코멘트 조금 더 남겼는데요, 다음 미션들에서도 충분히 다뤄질 수 있는 내용이니 이번 미션은 이만 머지할게요 ㅎㅎ
고생 많으셨어요 !

2021-07-09 00:31 UTC, wbluke commented on src/main/java/game/racingcar/RacingCarController.java
> +        List<Car> cars = carNames.stream().map(Car::new).collect(Collectors.toList());
```suggestion
        List<Car> cars = carNames.stream()
                .map(Car::new)
                .collect(Collectors.toList());
```

stream 로직은 항상 가공 단위로 줄바꿈을 하는 것이 가독성이 좋습니다 :)
(다른 곳에서는 잘 해주셨네요 ㅎㅎ)

2021-07-09 00:31 UTC, wbluke commented on src/main/java/game/racingcar/domain/Car.java
> +    public int position() {
`getPosition()`이겠네요 ㅎㅎ

2021-07-09 00:31 UTC, wbluke commented on src/main/java/game/racingcar/domain/Car.java
> +        return position == car.position && Objects.equals(name, car.name);
eq & hc 에 대한 이야기도 모임 시간에 언젠가 한번 다루게 될텐데요.
습관적으로 만드시는 분들도 많이 봤는데,
두 인스턴스의 동등성을 보장하려면 어떤 필드를 비교해야할지 한번 고민해 보세요 :)

(JPA 쪽 가서는 더 깊이 있는 이야기를 할 수 있을겁니다 ㅎㅎ)

2021-07-09 00:31 UTC, wbluke commented on src/main/java/game/racingcar/domain/GameCount.java
> +public class GameCount {
크 GameCount로 포장하고 validation까지 책임을 할당한 부분 너무 좋습니다 👍

2021-07-09 00:31 UTC, wbluke commented on src/main/java/game/racingcar/domain/RacingGame.java
> +                .filter(car -> car.position() == topScore(cars))
position getter를 사용하지 않고 Car에 메시지를 보내서 해결하면 어떨까요?

OOP에서 내가 상대방 객체의 정보를 가지고 어떤 행위를 해야하는 경우, 
`상대방 객체 내부의 정보를 가져올지, 아니면 상대방 객체에게 내 정보를 넘겨서 알아서 판단하도록 만들지` 를 항상 고민해보셔야 합니다 ㅎㅎ

2021-07-09 00:31 UTC, merged